### ISSUE TITLE
Add support for pulling CurtainSystems

### ISSUE THREAD

**Issue by enarhi** [BHoM/Revit_Toolkit#1034]
#### Description:
Add support for pulling CurtainSystems (in addition to currently supported CurtainWalls).

**Comment by vietle-bh** [comment]
Looks like the below has resolved this issue. Please reopen if not 👍 

https://github.com/BHoM/Revit_Toolkit/blob/6202e1799834d0fb8e7314587ecc1d68bca44e12/Revit_Core_Engine/Convert/Facade/FromRevit/CurtainWall.cs#L98
