### ISSUE TITLE
Add Engine Method for Placing Elements Along Linear MEP Objects

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Revit_Toolkit#1035]
#### Description:
Engine method creation for disconnecting linear MEP elements, placing accessory element (damper, valve) and reconnecting the linear MEP element on either side
 
Example: 
![image](https://user-images.githubusercontent.com/34316256/119695937-afa32b00-be1c-11eb-8621-a830fed17238.png)

Prototypes can be found here [https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F1035%2DAddEngineMethodforPlacingElementsonLinearObjects](url)

**Comment by pawelbaran** [comment]
@michal-pekacki happens to have some prototype written for this problem category, am I correct?

**Comment by kayleighhoude** [comment]
> @michal-pekacki happens to have some prototype written for this problem category, am I correct?

Awesome! Also have a couple of prototypes linked above, one in Dynamo/Python. We'll likely need to add connector properties to our linear MEP objects first.
