### ISSUE TITLE
Revit adapter not attaching

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Revit_Toolkit#1038]
#### Description:

seen on a couple of recent installations, the adapter in Grasshopper or Excel won't connect to revit, after checking the ports, that Revit is activated, restarting both softwares in various orders. 

> 1. Failed to connect to Revit. Please check if the BHoM Revit Adapter plugin is activated on the same ports as this adapter (default ports: 14128 input and 14129 output).
> Checking and updating ports on the Revit side: navigate to the BHoM ribbon tab in Revit, click Activate (if not active) and then Update Ports.
> Checking and updating ports on the BHoM side: extract the RevitSettings property of RevitAdapter object, then ConnectionSettings of RevitSettings, then extract/overwrite PushPort and PullPort properties.
> Please see the relevant Adapter/Setup Revit_Toolkit Wiki pages for more information.

**Comment by pawelbaran** [comment]
@JosefTaylor thanks for reporting. Is there a chance you could give me a call the next time this occurs? I have not heard about connection issues for some time already plus have not experienced anything during today's mass testing. Really curious what could that be, but cannot tell anything without seeing.

**Comment by JosefTaylor** [comment]
Haven't seen the error in a while, closing now.
