### ISSUE TITLE
SetProperty not pushing new section types to Revit

### ISSUE THREAD

**Issue by MatildaSvenssonBH** [BHoM/Revit_Toolkit#1078]
#### Description:

Wanted to update section types in Revit. Used SetProperty and set the Property.Name as the new section, but when pushed to Revit it doesn't actually change the sections. Instead I had to use SetRevitParameter and change the Type. 

#### Expected behaviour:

The SetProperty component should change the section type in Revit. 

#### Test file(s):

[Model Matching-IssueGitHub-MS.zip](https://github.com/BHoM/Revit_Toolkit/files/7143132/Model.Matching-IssueGitHub-MS.zip)

**Comment by pawelbaran** [comment]
Hi @MatildaSvenssonBH - thanks for reporting this! I have just looked up the file provided, but without a Revit model it is hard to tell anything.

I tried to reproduce the bug, in _UpdateType.gh/UpdateType.rvt_ files on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPush&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4), but everything works just fine, for all three type update mechanisms.

Following that, could you please try the above test file on your machine, and if it also works for you, could you please come back to your workflow and provide me with a minimal Revit file (preferably just one element that fails) in addition to Grasshopper? This would be really helpful. Thanks!

FYI @MartinHenriksen

**Comment by MatildaSvenssonBH** [comment]
Hi @pawelbaran - thank you! I tried the files you shared here and for me it only works for the two fist update mechanisms, the third one, SetProperty doesn't update the section, even if the success is true. Why is that?

**Comment by pawelbaran** [comment]
Following another round of investigation, I have the following findings:
- type update did not work on 4.2 😢 
- but... it works on the current master!

So I am closing this issue as out of date - please do not hesitate to reopen it in case you think the problem still occurs.
