### ISSUE TITLE
Revit 2020 Closing Upon Trigger of Pull and Push

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Revit_Toolkit#1125]
#### Description:
Using Alpha 211116, 211119, works well with Revit 2021, when prompting the same push/pull for 2020 it closes the session of Revit with no warning, can provide test file as necessary 

I tested back to 211108- the issue isn't occurring with this alpha file

**Comment by pawelbaran** [comment]
Thanks for reporting @kayleighhoude - a test file would be welcome, I have not noticed any issues on my end recently so can't reproduce/debug
