### ISSUE TITLE
Revit_Toolkit: Family Instance on MEP Curve Add Error Message

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Revit_Toolkit#1162]
#### Description:
Per recent issues explored with @pawelbaran and @michal-pekacki, let's add an error message regarding a union not being added to routing preferences prohibiting the placement of instance based objects onto MEP curves

![image](https://user-images.githubusercontent.com/34316256/150405583-f4f198a9-05cb-4297-bbb5-7f1dc03b4fda.png)

**Comment by michal-pekacki** [comment]
I can't rearrange this issue and fire damper placement works correctly for "None" union preferences - do you have the same @kayleighhoude?

**Comment by vietle-bh** [comment]
Closing this issue as we couldn't reproduce the error. Please reopen if necessary.
