### ISSUE TITLE
Ceiling Issue with Revit Adapter Pull

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Revit_Toolkit#1201]
#### Description:
Upon pulling a single ceiling, the pull works
Upon pulling multiple ceilings the following error(s) are thrown:

![CeilingPullIssue](https://user-images.githubusercontent.com/34316256/165868559-03d4c695-905b-411b-b033-374dd3354009.gif)

@alexissantella experienced this issue as well when pushing jsons of ceilings from Revit

@pawelbaran happy if this needs to be resolved in oM, felt like a Revit issue though!

#### Steps to reproduce:
Pull multiple ceilings

#### Expected behaviour:
All ceilings should pull

#### Test file(s):
The Revit file in this folder is the one we're using specifically:
[[(https://burohappold.sharepoint.com/sites/Direction/designtechnology/Presentation%20Library/Forms/AllItems.aspx?id=%2Fsites%2FDirection%2Fdesigntechnology%2FPresentation%20Library%2F220509%5FILFI%20Healthy%20Materials&viewid=1e550305%2D6bae%2D4408%2Daa47%2D4382a5155ad9)](https://burohappold.sharepoint.com/:u:/r/sites/Direction/designtechnology/Presentation%20Library/220509_ILFI%20Healthy%20Materials/ILFI%20Shoebox.rvt?csf=1&web=1&e=rrsf4e)]

**Comment by pawelbaran** [comment]
Yeah it looks like a RevitAPI issue at the 1st sight @kayleighhoude. But happy to have a look 'in the meantime' to check what's up. However, you forgot to add the test file folder 😉

**Comment by kayleighhoude** [comment]
@pawelbaran provided the test file link now! lmk if you need anything else @vietle-bh happy to dig into this with you as well

**Comment by pawelbaran** [comment]
If @vietle-bh is happy to dig, I am more than happy to step aside 😉 Is that true, @vietle-bh?
