### ISSUE TITLE
Remove old Versioning files

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#1216]
#### Description:
As in the title, remove all Versioning_XX.json files older than Versioning_53.

**Comment by FraserGreenroyd** [comment]
This should have been handled by the bot yesterday in this PR @pawelbaran https://github.com/BHoM/Revit_Toolkit/pull/1213

**Comment by pawelbaran** [comment]
Right, thumbs up for the @BHoMBot 👍
