### ISSUE TITLE
Error on failed Geometry Convert causes pull from links to fail completely

### ISSUE THREAD

**Issue by enarhi** [BHoM/Revit_Toolkit#1273]
#### Description:
As per:
![image](https://user-images.githubusercontent.com/6752345/200446092-d6e1961c-1709-4fbb-9750-5c771693c63e.png)

When attempting a pull including elements such as cylindrical faces which fail due to unsupported geometry converts, the resulting transform call fails due to an ambiguous call, thereby not pulling any objects. Given the fact that most models contain at least some walls with unsupported geometry converts, and we often need to pull their surfaces (where this error often occurs) to operate on after the pull, it is critical we support pulling these from links with proper handling so all other elements pull correctly. 

#### Steps to reproduce:
Pull walls from a linked model that includes unsupported wall geometries, such as curved walls. The Pull component will throw an error, and no elements will come through.

#### Expected behaviour:
All successful elements pulled, with the failing elements either returned with null geometry or bypassed with an error noting their failure similar to other pull behavior.

**Comment by pawelbaran** [comment]
Thanks for reporting @enarhi. I have tried to reproduce the issue [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%231273%2DPullFromLinkGeometryBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4), but without success. Could you please modify the files in the above folder to exhibit the faulty behaviour? Thanks!

**Comment by enarhi** [comment]
Tweaked the test script as the bug only occurs when `GeometryConfig` has `PullSurfaces` set to `True`.
![image](https://user-images.githubusercontent.com/6752345/201720407-a6338a26-ca2b-4e4d-a031-93a846516231.png)
