### ISSUE TITLE
Null exception on converting element boundaries

### ISSUE THREAD

**Issue by vietle-bh** [BHoM/Revit_Toolkit#1290]
#### Description:

When pulled from Revit, some items failed on a null exception due to having nurbs curves in their boundaries.

![image](https://user-images.githubusercontent.com/102604891/207303885-a96ac237-c4af-49f2-b7db-deee9320f251.png)

![image](https://user-images.githubusercontent.com/102604891/207303908-b4beb8ad-8523-42fc-9a6e-4ee6ec4dbad4.png)

![image](https://user-images.githubusercontent.com/102604891/207303926-548e710e-a2f6-4a2a-8693-e6e2dfc5b591.png)

#### Steps to reproduce:

Using the test files below, pull floors such as the one with ID 1321897 and the exception will throw.

#### Expected behaviour:

Only the first error message in the screenshot above should show.

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/Revit_Core_Engine-%231290-NullException?csf=1&web=1&e=5EAe64)

**Comment by pawelbaran** [comment]
The reported issue may origin from any convert that returns a `null` value, nurbs edge being just one potential case. Therefore, could you please align the title of the issue (also description potentially)? Thanks!

**Comment by pawelbaran** [comment]
Ah, plus please make sure you _always_ assign the issue - unassigned issues are usually never tackled as no one feels responsible.
