### ISSUE TITLE
Update BuiltInCategory Method to include all built in categories

### ISSUE THREAD

**Issue by travispotterBH** [BHoM/Revit_Toolkit#1295]
#### Description:

Current method for scraping built in categories from Revit does not include all built-in-categories, rather just a subset. 
For Example: Revisions is not available by scraping categories from `document.settings.Categories`
![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/96432552/209008713-f3258e44-1428-4485-bfd2-8669b37036f7.png)
![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/96432552/209008718-9a19c9d1-f32d-43bc-aa3f-e6e896f17453.png)

**Comment by pawelbaran** [comment]
As discussed the other day, I would say we need a method that would return `Dictionary<string, BuiltInCategory>` that would be the starting point for any further processing of labelled categories. Happy for you to give it a shot @travispotterBH - will gladly review and support your efforts 👍

**Comment by travispotterBH** [comment]
@pawelbaran Assigned
