### ISSUE TITLE
Revit_Toolkit: Invalid length of FramingElements when pushed to Revit

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/Revit_Toolkit#131]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by ZiolkowskiJakub** [comment]
Hi @jdarcyBHE,

There were couple changes made @IsakNaslundBh. Can you please check if you still have this issue?

**Comment by epignatelli** [comment]
Moving this to the 2.4 RC milestone, since it is labelled as bug.

**Comment by pawelbaran** [comment]
Considered closed with #376 - please reopen if the issue occurs again.
