### ISSUE TITLE
Trf non-conformal error when pulling some surfaces

### ISSUE THREAD

**Issue by enarhi** [BHoM/Revit_Toolkit#1330]
#### Description:
As per the image below, this error occurs when pulling certain elements with their surfaces. When the element is moved and repulled, the error goes away:
![image](https://user-images.githubusercontent.com/6752345/227298344-31effa46-f310-4480-a3ac-2a1cba82964f.png)

Specifically, this occurred with a pull of an element originally from an IFC import.

#### Steps to reproduce:
Pull from the test file, and the error will be thrown.

#### Expected behaviour:
Correct pulling of element and surfaces.

#### Test file:
[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Revit_Toolkit/%231330-TRF%20Non%20Conformal%20Error?csf=1&web=1&e=ehxPhw)

**Comment by pawelbaran** [comment]
The beauty of Revit... I managed to reproduce the error only to find out that according to Revit itself, the transform _is_ conformal:
![image](https://github.com/BHoM/Revit_Toolkit/assets/26874773/a511eb16-619f-437a-bd73-8ccba8372c92)

What else can be said 😃
