### ISSUE TITLE
Push type is not working properly as per CRUD method

### ISSUE THREAD

**Issue by ShashankBagane** [BHoM/Revit_Toolkit#1348]
Hi @BHoMBot I am facing issue with push type as it is not following as exactly with CRUD method. I have tried with every push type but it is same result that it is creating identical elements at the same location in revit. 

I have extracted elements from etabs and tried to send them to revit, but everytime it is creating identical elements at the same location which is wrong/is not the required result. Can you please suggest me which push type can exactly work that will only update(deletes the older one and replaces it with new one) and create(non-existing elements) like updateorcreate method I want to follow. 

Please let me know the solution for this. 

PFA of snip for your reference. 
![image](https://user-images.githubusercontent.com/94603543/230929528-66c360e9-7f3b-4318-9ec2-ef1309055df1.png)

**Comment by pawelbaran** [comment]
Thank you @ShashankBagane for reaching out. Is there a chance you could share the objects that you are trying to push to Revit, i.e. either a GH script with them internalised in a component or a .json file (you could use File Adapter to generate it or use `ToJson` Grasshopper component and then copy the text into a new file in notepad)?

I would be very surprised if there was a bug in one of the core `Push` actions in Revit_Toolkit - what I would rather expect is that you are losing the locations somewhere when transforming the pulled bars into columns to be pushed.

**Comment by ShashankBagane** [comment]
Hi @FraserGreenroyd @IsakNaslundBh @pawelbaran @teocomi do I have any updates on this issue ? If yes, please let me know. 

Thanks and Regards
Shashank B

**Comment by pawelbaran** [comment]
Thanks for the nudge @ShashankBagane. I have just had a look at the script - it worked perfectly fine when I run it on my machine, which can be seen in the clip below:

![shashank](https://user-images.githubusercontent.com/26874773/234955861-67087625-7981-4caf-9a21-251a76878433.gif)

**Comment by ShashankBagane** [comment]
@pawelbaran For the first time run (Like when we push it to revit for the first time) then it will be perfect and working fine. But when I change sectional properties any member like if I change two column sectional properties and in that case if I try to push it to revit then it won't work. I am getting errors like it is creating duplicates or identical items placed at the same position. Actually I need to delete the older one and replace it with the new one ( changed sectional properties). Hope this clears my issue to you. 

And one more thing I wanted to know which push type method are you using ? LIke I want to use more like update and create(it should create the new columns and update the older one which got updated with sectional properties(delete the older one that placed and replace it with new one)

Kindly let me know the solution for this. It will be very helpful. 

Thanks and Regards
Shashank B

**Comment by pawelbaran** [comment]
OK, so the challenge concerns updating the elements. To update, you need to use GH objects that already have reference to Revit elements (they need to know what they are in Revit, so to speak). In your current workflow, you always push objects that do not have that reference (we never modify data upstream in GH, so the push does not affect your objects being pushed). There are 2 ways of accessing objects with the reference:
- pulling elements from Revit
- using objects from output of `Push` components

Then you should be able to update the Revit elements using Push/UpdateOnly or Push/UpdateOrCreateOnly. Pseudocode could look like this:
![image](https://user-images.githubusercontent.com/26874773/235094800-4536d27b-cfc2-46e8-889d-aea5cf517540.png)

To check if your BHoM objects have reference to Revit elements, you can simply query `ElementId` and see if it has valid value:
![image](https://user-images.githubusercontent.com/26874773/235093874-df9eace3-cb22-4f7c-95ca-a58dd7187bfb.png)

Please note that updating Revit elements has quite a few limitations related to how Revit API works (e.g. inability to update location of floors, matching framing types by name etc.), so you'll need a bit of practice to make full use of the power of Revit_Adapter. But once you get there, you will never want to go back to Dynamo! 😉

**Comment by ShashankBagane** [comment]
Hay @pawelbaran I think you're mistaken me. I want to replace the element itself with new type. I don't want to change the parameter values. I want to change section or type of the element. 

**Like for ex:** If I have placed one column which has size of 1mx1m and it has been pushed extracted from etabs to revit and after analysis the section got revised to 1.2m x 1.2m so now if I extract that information form etabs and try to push it to revit in that case I am facing errors. Like it is placing the new column with 1.2 m x 1.2m at the same position/location but it is not deleting the older one 1m x 1m column when I use push type of updateandcreate method. My issue is simple but I know I am missing something that columns/any element should be revised after pushing it to revit. 

Hope this clears you my issue and kindly let me know the solution.

**Comment by pawelbaran** [comment]
@ShashankBagane it seems that your workflow is disjoint:
1. Pull from ETABS => push to Revit
2. Update ETABS model manually
3. Push/update the Revit model

In point 3., there is no link between the existing Revit and updated ETABS models. To achieve this, you could possibly push id of the correspondent ETABS bar when pushing framing to Revit the 1st time `(SetRevitParameter`), then you could always pull the Revit elements using filtering by parameter (using one of the `FilterByParameter` requests) - update should work as expected on such pulled elements  because they already have the required reference, as explained in my previous comment. I hope that helps 😉

**Comment by ShashankBagane** [comment]
Hi @pawelbaran Actually Create method can work for me as it may create duplicates but I manage to delete the older ones by referring to their ids and there by resolved my problem. Thanks for your help and support. I really appriciate that
