### ISSUE TITLE
Failed to pull walls from Revit

### ISSUE THREAD

**Issue by vietle-bh** [BHoM/Revit_Toolkit#1371]
#### Description:

Pulling walls previously only failed if the wall contains elliptical openings. Now this fails for all walls in the test file.

#### Steps to reproduce:

Try the first Pull node and the error will show.

![image](https://github.com/BHoM/Revit_Toolkit/assets/102604891/030b27d8-e028-4aa5-ac5d-a439e0aeee1d)

#### Expected behaviour:

This is what we could pull in the last milestone.
![image](https://github.com/BHoM/Revit_Toolkit/assets/102604891/88945334-0bdc-4787-859b-11dd90c9e07a)

#### Test file(s):
(Revit 2022)

[FromLink.zip](https://github.com/BHoM/Revit_Toolkit/files/11748724/FromLink.zip)

**Comment by pawelbaran** [comment]
OK, I think we are lucky this time! I had a look at the script and it looks like some weird UI glitch had happened in the script. `Query.FamilyName` component had grown a new leg named `S` and, what is worse, all wires got replugged to it!

![image](https://github.com/BHoM/Revit_Toolkit/assets/26874773/33e441b6-1aaf-4945-b69f-c50d037f64a8)

Everything works fine after replacing the invalid component with a new one (I made the update in test resources, so should be good now). I will close the issue, please reopen @vietle-bh if the 'fix' is wrong/insufficient from your perspective.

FYI @FraserGreenroyd - no clue how did that happen, the only recent change to the component is [this commit](https://github.com/BHoM/Revit_Toolkit/commit/e6324c06d26be8828d3fba1714f9956950e72a70#diff-2c79c5f01d5a167a5419bfa7ffed9d28c1d012315454f6a98dbb246ac1b1ba36), which I would expect to be nonharmful 🤨

**Comment by vietle-bh** [comment]
I've just tested this again and it worked. I used the same GH file from yesterday and couldn't see the additional "S" output, probably because I installed the latest test artefact earlier today.

All is back to normal now!

![image](https://github.com/BHoM/Revit_Toolkit/assets/102604891/3bccc063-0d83-4fec-9cf9-2607c715897a)
