### ISSUE TITLE
Optimize Facade Element Pulls

### ISSUE THREAD

**Issue by enarhi** [BHoM/Revit_Toolkit#1389]
#### Description:
Currently, pulling facade elements take quite a long time, especially when dealing with large collections of openings, for example. We should look to optimize the frame edge pulling process to minimize performance impact, skipping frame edge profile geometry more effectively and handling the overall conversion of revit window/curtain wall panel/etc to Facade Element more efficiently overall.

#### Steps to reproduce:
Pull many facade elements, and wait.....

#### Expected behaviour:
Faster pulling of elements to improve UX.

#### Test file(s):
[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/Revit_Toolkit/Pull/PullFacadeElements.gh?csf=1&web=1&e=3Tl90e)

**Comment by pawelbaran** [comment]
Self-reminder: may be worth tackling together with https://github.com/BHoM/Revit_Toolkit/issues/1373 (or at least with it in mind). Also adding more assignees - first come first labour 😃
