### ISSUE TITLE
`BH.oM.Physical.Elements.Column` material convert issue

### ISSUE THREAD

**Issue by michal-pekacki** [BHoM/Revit_Toolkit#1407]
#### Description:

`BH.oM.Physical.Elements.Column` object has different material after exporting to json file:

- `SolidMaterial` when converting directly from revit
![image](https://github.com/BHoM/Revit_Toolkit/assets/71321938/2d0a055e-6911-4185-8467-9a2811421f65)

- `Concrete` after exporting to json file:
![image](https://github.com/BHoM/Revit_Toolkit/assets/71321938/343c3322-7023-4af1-bd1e-77efee2ab1a3)

#### Steps to reproduce:

Issue has been found during `PullColumnLoaction` testing procedure.

**Comment by pawelbaran** [comment]
Thanks for raising @michal-pekacki. I have investigated the test script and the error is a false flag actually - it is an improvement introduced by tweaking `FramingMaterial` query in https://github.com/BHoM/Revit_Toolkit/pull/1395/files. I will close this issue, we need to update our testing procedure and it will be all good 👍
