### ISSUE TITLE
Diffing: should 'Edited by' parameter be ignored by default?

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#1430]
#### Description:
While doing various diffing exercises, I noticed we keep on ruling out `Edited by` parameter - maybe we should simply add it to the ignored set by default? Thoughts against?

@alelom FYI the parameter informs about the last user that 'touched' a Revit element. So as long as it may be an important piece of information in many contexts, we usually do not care about it in diffing.

**Comment by alelom** [comment]
It makes sense to add it to the default `ignore` setting for RevitDiffing, yes!
