### ISSUE TITLE
'Medium' mesh quality

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#1439]
#### Description:
Revit operates with 3 view qualities: `Coarse`, `Medium` and `Fine`. While meshing, these enum values get converted to a mesh quality factor that needs to be in range between 1 and is passed to the triangulation function. When writing the original code I took the most obvious values off the top of my head, being:
- `Coarse` => 0.0
- `Medium` => 0.5
- `Fine` => 1.0

These work fine in general, but I recently ran into performance-related issues caused by the `Medium` value, being a default one in the diffing processes (in general we do not want to use neither of the remaining two, one being too coarse the other too fine). I started investigating how does the mesh quality factor affect mesh size and visual quality. I ran a sensitivity study using a set of Revit elements of different geometrical complexity, from simple cuboids to doubly curved surfaces. I meshed them with different mesh quality factors between 0.0 and 0.5, with the following results:

Top row - vertex count
Bottom row - face count
![image](https://github.com/BHoM/Revit_Toolkit/assets/26874773/1cec2704-9691-4036-9d04-733c2324cf94)

It can clearly be seen that the mesh size and performance starts to grow quickly for mesh quality factors >0.3, which means that we would ideally use a value of 0.3 as `Medium`. I decided to verify whether this would not affect the visual experience of the users, results below.

Visual quality - 0.0
![image](https://github.com/BHoM/Revit_Toolkit/assets/26874773/12c79d6b-2d90-4897-a489-550bb857225f)

Visual quality - 0.1
![image](https://github.com/BHoM/Revit_Toolkit/assets/26874773/1646dad4-e27a-41f0-96b0-5cb79c55f4c6)

Visual quality - 0.2
![image](https://github.com/BHoM/Revit_Toolkit/assets/26874773/4af5b08c-60fe-47bb-a411-3267aed00f08)

Visual quality - 0.3
![image](https://github.com/BHoM/Revit_Toolkit/assets/26874773/df88cc8c-8609-4e17-8566-346b0d338152)

Visual quality - 0.4
![image](https://github.com/BHoM/Revit_Toolkit/assets/26874773/2f14e876-0738-481e-ba22-0232c5895028)

Visual quality - 0.5
![image](https://github.com/BHoM/Revit_Toolkit/assets/26874773/0504e4c3-cff4-450c-8924-404558cbea67)

In my opinion the difference in visual experience between 0.3 and 0.5 is not worth the performance hit, so I would consider changing the mesh quality factor for `Medium` quality from 0.5 to 0.3. This, however, would affect the existing diffing workflows because all elements would flag as geometry changed. This of course is a breaking change, which would require careful treatment, i.e. a piece of information to be embedded in the diffing workflows that would inform the user about incompatibility between 7.0 and older extractions and 7.1 and above.

I believe it is worth the game, but wanted to check with you:
- do you agree the mesh quality achieved with factor 0.3 is visually acceptable as default preview?
- do you agree it makes sense to make an effort and introduce the breaking change to shrink the extreme case meshes by >90%?

For these interested, the sensitivity study is available [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%231439%2DMediumMeshQuality&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

**Comment by al-fisher** [comment]
> In my opinion the difference in visual experience between 0.3 and 0.5 is not worth the performance hit, so I would consider changing the mesh quality factor for Medium quality from 0.5 to 0.3.

Would definitely agree with this. Worth doing a quick study on a few other standard families to see similar results if not already done. But this looks like a no brainer to me for default mesh preview value.

Then also thinking specifically for the mesh required for diffing - this is required just to be representative to track and naturally flag when geometries change. So for diffing specifically I don't see issues with the mesh being really quite coarse as chances of geometry changes happening which the mesh is _too_ coarse to capture is very low/negligible.

**Comment by FraserGreenroyd** [comment]
I'd agree with @al-fisher that the diffing caused by those changes would be negligible.

I would ask whether there is benefit to making the decision user-controlled, allowing users to choose how coarse to set their mesh for such a workflow, just to provide full flexibility to the users without constraining them?

This may be an out-of-scope question/desire though for the purpose of this particular issue so happy for it to not be answered if so - just raising it as a question to capture just in case 😄

**Comment by pawelbaran** [comment]
Thanks @al-fisher @FraserGreenroyd for the replies - responses below ⬇️ 

> Would definitely agree with this. Worth doing a quick study on a few other standard families to see similar results if not already done. But this looks like a no brainer to me for default mesh preview value.

Yeah as mentioned in the issue description, the study is based on a set of Revit elements of different geometrical complexity, from simple cuboids to doubly curved surfaces, so it is representative I believe - of course more testing to be done before ultimate merge.

> Then also thinking specifically for the mesh required for diffing - this is required just to be representative to track and naturally flag when geometries change. So for diffing specifically I don't see issues with the mesh being really quite coarse as chances of geometry changes happening which the mesh is _too_ coarse to capture is very low/negligible.

The rationale behind not using the extreme coarse in diffing is preview - at 0.0 factor the curved surfaces look really rough, so I would rather stick to the lowest values that make the meshes look better than Minecraft 😃 

> I would ask whether there is benefit to making the decision user-controlled, allowing users to choose how coarse to set their mesh for such a workflow, just to provide full flexibility to the users without constraining them?

You can control it in script-based workflows (one can pick between `Coarse`, `Medium` and `Fine` meshing), but I do not expose this option in automated processes - less things to break basically 😉
