### ISSUE TITLE
Is it not possible to apply additional user parameters?

### ISSUE THREAD

**Issue by paduk-dev** [BHoM/Revit_Toolkit#1509]
As an example, add a parameter to the Revit Wall object and enter a value.
I converted this to BHoM Object. And then I deleted this wall.
Now I push the BHoM Object. In this case, the wall was created, but the parameters I customized were there, but the values ​​did not come in.

Is this a bug? Was this intentional? Or did I make a mistake?
Below is my simple test code.

```
public Result Execute(ExternalCommandData command_data, ref string message, ElementSet elements)
    {
        var ui_doc = command_data.Application.ActiveUIDocument;
        var doc = ui_doc.Document;

        var reference = ui_doc.Selection.PickObject(ObjectType.Element, " Pick Object");
        var element = ui_doc.Document.GetElement(reference.ElementId);
        
        var wall = element as Autodesk.Revit.DB.Wall;
        var bhom = wall.FromRevit(Discipline.Physical);
        
        using (var trans = new Transaction(ui_doc.Document, "delete wall"))
        {
            trans.Start();
            if (wall is not null)
            {
                ui_doc.Document.Delete(wall.Id);
                trans.Commit();
            }
        }
        TaskDialog.Show("Revit", "Delete Wall.");
        
        try
        {
            var adapter = new RevitAdapter(null, true);
            adapter.Push(bhom);
            TaskDialog.Show("BHoM", "BHoM Wall Push.");
            return Result.Succeeded;
        } catch (Exception e)
        {
            TaskDialog.Show("Exception", $"{e}");
            return Result.Failed;
        }
    }
```

**Comment by pawelbaran** [comment]
Thanks @paduk-dev for raising this. Actually, there are two separate objects that store the pulled parameters as well as parameters to push:
- [RevitPulledParameters](https://github.com/BHoM/Revit_Toolkit/blob/develop/Revit_oM/Parameters/RevitPulledParameters.cs)
- [RevitParametersToPush](https://github.com/BHoM/Revit_Toolkit/blob/develop/Revit_oM/Parameters/RevitParametersToPush.cs)

The reason for splitting it up this way is to avoid trying to update all parameters any time an object is pulled and then updated. So what you would need to do to push parameter values is transferring them from one fragment to another, which is as simple as calling [`GetRevitParameters`](https://github.com/BHoM/Revit_Toolkit/blob/develop/Revit_Engine/Query/GetRevitParameters.cs) against the pulled wall and then passing them to [`SetRevitParameters`](https://github.com/BHoM/Revit_Toolkit/blob/develop/Revit_Engine/Modify/SetRevitParameter.cs).

Hopefully that makes sense, please feel free to ask again if further clarification is needed 👍
