### ISSUE TITLE
Revit_Toolkit: Pull Panel Planar returns geometry at the slab centreline

### ISSUE THREAD

**Issue by rwemay** [BHoM/Revit_Toolkit#161]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
Considered closed with #376 - please reopen if occurs again.
