### ISSUE TITLE
Revit_Toolkit: pull panels makes some openings part of the panel edge

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Revit_Toolkit#164]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
Closing as this should be resolved with #376
