### ISSUE TITLE
Revit_Toolkit: pull framing elements returns FreeFormProfile for all sections

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Revit_Toolkit#171]
### Description
US Template family sections come in as freeform, and these freeform sections often are invalid.

### Test Script
https://burohappold.sharepoint.com/:f:/s/BHoM/Em2GjEWXzx1Os0k8uPhXDjIBhjiu_Po8aJ4hXoDL4r16LQ?e=NDO002

**Comment by enarhi** [comment]
Adding to this, the free form profiles have errors in some cases leading to an inability to recreate the framing element / push it further downstream. See attached. 

![image](https://user-images.githubusercontent.com/6752345/50459401-992cd880-091f-11e9-97dd-10149aaefbec.png)

**Comment by JosefTaylor** [comment]
The first part of this issue, that sections come in as FreeForm, is a problem with the US Structural Template for Revit- we didn't know we were meant to fill in the 'section type' parameter. This will be fixed soon.

The second is an issue with the Revit Toolkit.

**Comment by pawelbaran** [comment]
I could not replicate the second bug after #376, therefore closing this one - please reopen in case this occurs again.
