### ISSUE TITLE
Revit_Toolkit: make pulling independent of the analytical model

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#20]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by ZiolkowskiJakub** [comment]
This should be solved by implementation of Physical Objects ([BHoM PR](https://github.com/BHoM/BHoM/pull/418))

**Comment by pawelbaran** [comment]
Closed with #376.
