### ISSUE TITLE
Revit_Toolkit: Stop providing default materials

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Revit_Toolkit#206]
When pulling structural objects from Revit, the adapter currently provides a default material if nothing matching is found in the internal databases.

This is dangerous, as for an engineer using the toolkit probably will presume that everything has worked fine, even if in fact to match was found.

If no matching material is found, the toolkit should instead return an empty material with as many properties as can be found set, as well as a warning raised stating that a dummy material has been provided.

**Comment by rwemay** [comment]
Thanks @IsakNaslundBh , agree with this approach. @ZiolkowskiJakub hope you agree.

**Comment by ZiolkowskiJakub** [comment]
I agree. I will look at it today as discussed with @IsakNaslundBh 

@pawelbaran
