### ISSUE TITLE
Revit_Toolkit: Keep Building Element normal when pull push

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#219]
we need to keep normal orientation - point order
![image](https://user-images.githubusercontent.com/26113670/51622702-0cca0180-1f2f-11e9-8fd4-ea00fdb5aa31.png)

after pull and push

![image](https://user-images.githubusercontent.com/26113670/51622690-03409980-1f2f-11e9-8f6c-b3a3a0fef6fd.png)

**Comment by michaldengusiak** [comment]
to be fixed with #371

**Comment by pawelbaran** [comment]
Closing that as a duplicate of #371
