### ISSUE TITLE
Revit_Toolkit: Pulling slabs without analytical model enabled

### ISSUE THREAD

**Issue by johannaisak** [BHoM/Revit_Toolkit#227]
Pulling slabs should be possible without analytical model enabled. @rwemay : "When the analytical model is available, pull should access this. When it is not available, pull should take the top surface of the slab and use this as the analytical panel. For framing elements, likewise – if analytical is available, then use it, if not, use the location line of the framing element."

**Comment by pawelbaran** [comment]
Closed with #376.
