### ISSUE TITLE
Grids - Multi-segment not coming through

### ISSUE THREAD

**Issue by rwemay** [BHoM/Revit_Toolkit#23]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by rwemay** [comment]
Multi segmented grids are still coming through as multiple grid/objects. Believe these should come through as an ICurve (polycurve). @pawelbaran thoughts?

**Comment by pawelbaran** [comment]
Oh, it hid at the very bottom of the list! Should be easy to fix, I'll try to tackle it this week.
