### ISSUE TITLE
Revit_Toolkit: Pull for curved framing elements does not return a location curve

### ISSUE THREAD

**Issue by arosario2** [BHoM/Revit_Toolkit#235]
I tried to pull curved beams from Revit and they came through but they do not have a location line because they are curved. Is this a known issue and if so, what is the suggested workaround? 

![image](https://user-images.githubusercontent.com/47364021/52293416-a203c780-292b-11e9-943d-f6e74e0316fa.png)

![image](https://user-images.githubusercontent.com/47364021/52293469-c52e7700-292b-11e9-94e8-f2ba22a9753e.png)

**Comment by ZiolkowskiJakub** [comment]
Hi @enarhi,

Unfortunately BHoM FramingElement is defined by Line therefore I am not able to Push it location as Curve:
[BHoM FramingElement](https://github.com/BHoM/BHoM/blob/master/Structure_oM/Elements/FramingElement.cs)

If you have any consideration about this please talk with @al-fisher or @rwemay 

I implemented workaround in #243 

The work around is as follow:
1. Pull Framing Elements from Revit as GenericObject
2. Retrieve Location from GenericObject
3. You can then "manually" create BHoM FramingElement from GenericObjetcs or use GenericObject straight away (it should also contains all parameters)

Please let me know if this helps.

**Comment by ZiolkowskiJakub** [comment]
Here is Example how to pull (any) specific Family as GenericObject:

![image](https://user-images.githubusercontent.com/16777757/52848950-e64f4e80-3107-11e9-8394-310b2b70d140.png)

Script can be found
[here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue235-PullCurvedFramingElements?csf=1&e=udcPQk)

**Comment by rwemay** [comment]
Hi @ZiolkowskiJakub , the framing element location curve should be an ICurve. Can someone raise an issue on the BHoM for this (@IsakNaslundBh ?)

**Comment by IsakNaslundBh** [comment]
https://github.com/BHoM/BHoM/issues/331

Raised already. One of the issues I did not get around to fix before OS.

Can put as a priority for next week but will need to coordinate with @ZiolkowskiJakub.

**Comment by enarhi** [comment]
Thanks all, excited to see this in place. @ZiolkowskiJakub , throw a review request my way as soon as this is implemented in Revit_Toolkit (after bhom implementation of course) and I will immediately review, as we have a project test case that I want to get this working on ASAP.
