### ISSUE TITLE
Revit_Toolkit: Panels made from arcs and freeform Panels

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/Revit_Toolkit#238]
Currently it seems Revit isn't able to take planar panels made from Arcs or freeform panels.

[Panel test.zip](https://github.com/BHoM/Revit_Toolkit/files/2851951/Panel.test.zip)

**Comment by enarhi** [comment]
This is the same as #236 , high priority as it restricts functionality on a wide array of applications. @ZiolkowskiJakub , let me know if additional support would help, I have some time over the next couple weeks to plug in as is needed.

**Comment by FraserGreenroyd** [comment]
Moved to 2.4RC milestone as @pawelbaran is working on this and should be done during the RC sprint.

**Comment by pawelbaran** [comment]
Closed with #376.
