### ISSUE TITLE
Revit_Toolkit: Adjust Material deafult

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#250]
Adjust default to allow simulation and avoid errors

[BuroHappoldEngineering/EnergyPlus_Toolkit#5](https://github.com/BuroHappoldEngineering/EnergyPlus_Toolkit/issues/5)

**Comment by pawelbaran** [comment]
@michaldengusiak @ZiolkowskiJakub is this still relevant?

@FraserGreenroyd I am making you the only assignee - please feel free to pass the issue to a relevant person in your team, I will not be able to resolve it.

**Comment by FraserGreenroyd** [comment]
For this milestone, will be looked at by @rboultonBH and myself by feature milestone end.

**Comment by FraserGreenroyd** [comment]
I am happy that recent changes to the framework render this issue unnecessary for the time being. Any material changes can be made in visual programming workflows if further changes are needed or this issue can be reopened with more specific information of what needs adjusting as necessary.
