### ISSUE TITLE
Revit_Toolkit: Parameter Mapping for Push

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/Revit_Toolkit#258]

**Comment by pawelbaran** [comment]
@ZiolkowskiJakub is that still relevant? If so, could you please add an informative description, otherwise close?

**Comment by ZiolkowskiJakub** [comment]
This is implementation of Parameter Mapping as described here #256 but for Push

Parameter Mapping is used to map between Revit Element parameter and BHoM object properties. If parameter mapping would be implemented for Push it would allow to easily copy value of BHoM object property to Revit Element parameter.
