### ISSUE TITLE
Revit_Toolkit: R1 Generating Views

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#259]
Lets get BHoM do production work.. tiny small steps here is first set

- [x] ViewType
<img src="https://user-images.githubusercontent.com/26113670/53945230-119add00-40b9-11e9-91eb-50a2f96fc80b.png" width=100>

- [x] ViewTemplates

- [x] CreateViewsFromReferencesAndApplyTemplates

- [x] Elements.FilterByParameterValueAndCondition

- [x] View.GetByType

- [x] Element.Delete

**Comment by ZiolkowskiJakub** [comment]
Samples [link](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue259-ViewGeneration?csf=1&e=GahzMe)
