### ISSUE TITLE
Revit_Toolkit: Profile extraction test script

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Revit_Toolkit#261]
Need to create a Revit model with more or less all possible scenarios of different section families, in terms of type, to be able to test the section extraction from Revit .

Starting point to load in all standard families and create a beam and column of each type.

**Comment by ZiolkowskiJakub** [comment]
Hi @IsakNaslundBh, @pawelbaran,

How are we progressing with this issue? Do you need anything from my side to finish this task?

**Comment by pawelbaran** [comment]
No action on my end yet, looking forward to taking care of that in the coming months...

**Comment by pawelbaran** [comment]
Profile extraction script prepared, so can be closed.
