### ISSUE TITLE
Revit_Toolkit: R2 Generating Sheets

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#263]
Step 2 time for sheets

- [ ] Sheet Collector
- [ ] Elements.FilterByParameterValueAndCondition
- [ ] View.ViewPortBoxCenter
- [ ] CreateSheetsFromViewsAndReferenceSheet

**Comment by michaldengusiak** [comment]
sample [link](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue263-SheetGeneration?csf=1&e=5czi7B)

**Comment by FraserGreenroyd** [comment]
To be left for next milestone 3.1 after discussion with @rboulton-BH considering other current priorities.

**Comment by pawelbaran** [comment]
This issue has been stale for long enough to close.
