### ISSUE TITLE
Revit_Toolkit: Add ViewDuplicateOption.WithDetailing

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#264]
Create `ViewPlan` using Autodesk.Revit.DB.ViewDuplicateOption.WithDetailing so we have detailing included ie. color legend, scope box etc

for test file and python text node please see here #259

**Comment by FraserGreenroyd** [comment]
Linked with #263 
To be left for next milestone 3.1 after discussion with @rboulton-BH considering other current priorities.

**Comment by pawelbaran** [comment]
This issue has been stale for long enough to close.
