### ISSUE TITLE
Revit_Toolkit: Centralise BHoM assemblies folder into %AppData%\BHoM

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Revit_Toolkit#272]

**Comment by awakeman** [comment]
I think in this case it is as simple as changing this line to point to the user's `%AppData%\BHoM\Assemblies` folder.

https://github.com/BHoM/Revit_Toolkit/blob/2b5af55a57b9d643e3be4f10eda56839057b9d3e/Revit_UI/Files/BHoM.Addin#L5

**Comment by ZiolkowskiJakub** [comment]
Hi @awakeman,

I am looking at this issue now and there seems to be problem with Revit versioning.  Adapter_Revit_UI, Engine_Revit_UI and Revit_UI are Revit version dependent so we need to be able to store multiple versions of these dlls. How do we imagine folder structure to cover that?

Currently we store the files in separate Revit addin folders 2018, 2019 etc...

```
            string versionNumber = uIControlledApplication.ControlledApplication.VersionNumber;
            string path = Environment.GetEnvironmentVariable("APPDATA") + @"\Autodesk\Revit\Addins\" + versionNumber +  @"\BHoM";
            BH.Engine.Reflection.Compute.LoadAllAssemblies(path);
```

@rwemay, @al-fisher

**Comment by ZiolkowskiJakub** [comment]
Hi,

We had catch up with @epignatelli and @IsakNaslundBh and here is the summary:
1. We need to rename following dlls depends on Configuration:
- Revit_UI.dll to Revit_UI_2018.dll, Revit_UI_2019.dll 
- Adapter_Revit_UI.dll to Adapter_Revit_UI_2018.dll, Adapter_Revit_UI_2019.dll 
- Engine_Revit_UI.dll to Engine_Revit_UI_2018.dll, Enginer_Revit_UI_2019.dll 
2. Create two copies of BHoM.Addin and save it as  BHoM_2018.Addin and BHoM_2019.Addin (update paths inside file accordingly) **Temporary solution**
3. Update code for RevitListener:
``
string versionNumber = uIControlledApplication.ControlledApplication.VersionNumber;
BH.Engine.Reflection.Compute.LoadAllAssemblies();
``

**These changes have to be reflected in BHoM Installer**
