### ISSUE TITLE
Revit_Toolkit - Implement method for renaming drawing files

### ISSUE THREAD

**Issue by DanielJonssonBH** [BHoM/Revit_Toolkit#28]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by ZiolkowskiJakub** [comment]
Hi @DanielJonssonBH,

I created script which does to job. You can add your modifications to it:
![image](https://user-images.githubusercontent.com/16777757/51391665-8e362400-1b2a-11e9-9203-62d2ab133468.png)

Script will be available in samples repository soon:
[samples](https://github.com/BHoM/samples/pull/8)
[script]()
