### ISSUE TITLE
Revit_Toolkit:  Pull Using ID's as Filters

### ISSUE THREAD

**Issue by emidio-piermarini** [BHoM/Revit_Toolkit#283]
Seems the SelectionFilterQuery will not pull no matter what ID I use

**Comment by ZiolkowskiJakub** [comment]
Hi @emidio-piermarini,

I tested it and it worked fine on my machine.

Sample available [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue183-PullByElementId?csf=1&e=d65lqI)

Can you please provide files did not work with you? 

Thanks in advance.

**Comment by ZiolkowskiJakub** [comment]
@emidio-piermarini this also could be Toolkit related issue. Can you please provide Grasshopper script and save it into the above folder?

Thanks!

**Comment by ZiolkowskiJakub** [comment]
Hi @emidio-piermarini,

Can you please test it again. Please remember to follow steps described below if you have not done it already:
[Revit_Toolkit - Working with source code](https://www.yammer.com/burohappold.com/threads/209594447814656)

Thanks in advance.

**Comment by ZiolkowskiJakub** [comment]
As tested with @pawelbaran: The issue is related to Grasshopper_Toolkit. It seems Grasshopper Enumerables are casted to IEnumerable<object>:

```
        public static IEnumerable<int> ElementIds(this FilterRequest filterRequest)
        {
            if (filterRequest == null)
                return null;

            if (!filterRequest.Equalities.ContainsKey(Convert.FilterRequest.ElementIds))
                return null;

            return filterRequest.Equalities[Convert.FilterRequest.ElementIds] as IEnumerable<int>;
        }
```

It means that `filterRequest.Equalities[Convert.FilterRequest.ElementIds]` has to be treated
 as `IEnumerable<object>`

The quick workaround will be applied by @pawelbaran
