### ISSUE TITLE
Revit_Toolkit: columns do not get pushed due to FamilyPlacementType bug

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#292]
![image](https://user-images.githubusercontent.com/26874773/57712762-718da100-7671-11e9-9abf-4d92585f62dd.png)

`CurveDrivenStructural` also needs to be added.

@IsakNaslundBh following our chat, could you please implement it in your current PR? Btw, @ZiolkowskiJakub do you know a way to check which `FamilyPlacementTypes` are used by column families? Maybe some of the removed ones are fine too.

**Comment by ZiolkowskiJakub** [comment]
Hi @pawelbaran,

I do not know easy way to check available FamilyPlacementType for certain categories... I believe current settings was working only for some of the column Families. We could check it by querying our existing internal library as workaround.

**Comment by pawelbaran** [comment]
This could be a nice baby step for a BH library parser, @al-fisher @rwemay?

**Comment by rwemay** [comment]
Yes could be. There are surely only a limited number of placement types per family category, and we can check the BHoM object properties as to which to use? I feel like I've missed something here though...!

**Comment by pawelbaran** [comment]
FamilyPlacementType is an enum that defines what sort of information does the family need to be instantiated in space [link](http://www.revitapidocs.com/2015/2abb8627-1da3-4069-05c9-19e4be5e02ad.htm). If we scan our BH column families, we can make sure that we support all of them.

**Comment by pawelbaran** [comment]
Already resolved.
