### ISSUE TITLE
Revit_Toolkit: Pull->Push->Pull structural framing elements failing

### ISSUE THREAD

**Issue by rwemay** [BHoM/Revit_Toolkit#293]
When you create a (concrete) beam, column, you can pull these from Revit (with warnings), push them back again, but cannot then re-pull them. 

Test script here: https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue293-Pull-Push-Pull%20Framing%20Element?csf=1&e=ivwUZm

![image](https://user-images.githubusercontent.com/15233608/57916655-349cf680-788b-11e9-92b7-03e92da851e9.png)

**Comment by pawelbaran** [comment]
@rwemay is that columns?

**Comment by ZiolkowskiJakub** [comment]
Update: This has been solved by @IsakNaslundBh  here:
#315 

@rwemay
