### ISSUE TITLE
Revit_Toolkit: Push framing elements pushing many instances/copies

### ISSUE THREAD

**Issue by rwemay** [BHoM/Revit_Toolkit#297]
264 framing elements input to push, over 1,600 elements created in Revit with lots of identical instance warnings.

Test script saved here: https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue297-Push%20Framing%20Elements%20Multiple%20Copies?csf=1&e=7XZumG

**Comment by ZiolkowskiJakub** [comment]
Hi @rwemay,

In my case there was over 1600 warnings but only 264 elements created:
![image](https://user-images.githubusercontent.com/16777757/58244292-39a9ec00-7d4a-11e9-89e1-4cc281bc650d.png)

Looking at the first one:
![image](https://user-images.githubusercontent.com/16777757/58244375-5fcf8c00-7d4a-11e9-86a1-9d470cbdcdec.png)

There are Framing Elements with the same location cure on the list. Sample:
![image](https://user-images.githubusercontent.com/16777757/58244190-0d8e6b00-7d4a-11e9-87ba-c4c1e2027afa.png)

If locations are the same it will show the warrings in Revit. 

Full Report:
[190513_Steel Truss Example_Error Report.zip](https://github.com/BHoM/Revit_Toolkit/files/3211546/190513_Steel.Truss.Example_Error.Report.zip)

I am not quite sure what kind of different behaviour you would expect in this case. Should Revit_Toolkit detect elements with similar location and do not create it?

**Comment by rwemay** [comment]
Czesc @ZiolkowskiJakub , thanks for this - looks like an issue with the GH script rather than Revit, although the number of warnings is odd. Ill check again, suspect there’ll be some duplicate curves in GH causing the issue, apologies, should have checked more closely!

**Comment by rwemay** [comment]
As suspected this was an issue with the script not the adapter, sorry @ZiolkowskiJakub , thanks for quick response!
