### ISSUE TITLE
Revit_Toolkit: Conversion missing (BHoM Polyline to Revit Curve)

### ISSUE THREAD

**Issue by nirbhay93** [BHoM/Revit_Toolkit#306]
![image](https://user-images.githubusercontent.com/33544613/58631791-45c11b00-8301-11e9-8bcf-0f4bea7026d5.png)

**Comment by ZiolkowskiJakub** [comment]
Hi @nirbhay93,

Sorry but forgot to ask about the sample file we were testing the push. Can you please save Grasshopper script and rhino file here:

[Sample](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue306-PolylineToCurve?csf=1&e=WVbMGt)

Thank you in advance.

**Comment by nirbhay93** [comment]
Yes, sure, @ZiolkowskiJakub. Did it.

Regards.

**Comment by pawelbaran** [comment]
@nirbhay93 thanks for flagging this up! I have just looked into the issue: looks that the convert method is in place for `Polyline` with 2 control points (technically a line). In case of more than 2 control points, the convert is not valid as there is no Revit-type curve containing of more than one segment - it needs to be come a `CurveArray` or `CurveLoop`, which is already a different class.

Your test file, however, works on a Polyline containing only 2 points, so at the moment it works fine. Therefore I am closing this issue. Please feel free to reopen in case I misunderstood something. Thanks!
