### ISSUE TITLE
Revit_Toolkit: Add Space Location Point

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#307]
bring back Space - location point

**Comment by ZiolkowskiJakub** [comment]
Hi @michaldengusiak,

Where you want to store this data?

**Comment by FraserGreenroyd** [comment]
@ZiolkowskiJakub I'd use this PR as a basis: https://github.com/BHoM/BHoM/pull/501

**Comment by michaldengusiak** [comment]
@ZiolkowskiJakub  -  ready for you

**Comment by michaldengusiak** [comment]
@ZiolkowskiJakub  can we try to add this now, thanks
