### ISSUE TITLE
Revit_Toolkit: Add posibility to place modelInstance Two-levelbased

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Revit_Toolkit#308]
Similar to the Point based and Curve based, good to get ability to place TwoLevelBased ones as well.

**Comment by pawelbaran** [comment]
I do not know the issue, but just bumped into the method below. Hopefully it will help.
https://github.com/BHoM/Revit_Toolkit/blob/d740e15aa7ce002e49089dfadd73d7e74e5c688b/Engine_Revit_UI/Convert/Revit/ToRevit/Element.cs#L88

**Comment by IsakNaslundBh** [comment]
Sorry, not very descriptive...

This was related to https://github.com/BHoM/Revit_Toolkit/pull/303#issuecomment-499006608

Basically being able to place out columns using the family generation script made by @ZiolkowskiJakub
