### ISSUE TITLE
Revit_Toolkit: Create family Instance for DetailItem does not work

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/Revit_Toolkit#309]
https://github.com/BHoM/Revit_Toolkit/pull/303#pullrequestreview-244745533

**Comment by ZiolkowskiJakub** [comment]
Further Investigation:
Detail Item families has FamilyPlacementType.ViewBased placement type which has not been implemented.

**Comment by FraserGreenroyd** [comment]
To be left for next milestone 3.1 after discussion with @rboulton-BH considering other current priorities.

**Comment by pawelbaran** [comment]
This must have stayed open after the issue has been resolved - it works perfectly fine now.
