### ISSUE TITLE
Revit_Toolkit: Migrating to Physical objects

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Revit_Toolkit#312]
Updating Revit toolkit to point to physical objects giving the changes here:

https://github.com/BHoM/BHoM/issues/494

Summary of updates:

- Should now support Physical Wall,Roof and Floor instead of Architectural.

-Should now support Physical IFramingElement instead of structural

- Clean-up of material management to make sure BOTH structural and Environmental material are extracted, not just one of them.

**Comment by michaldengusiak** [comment]
@ZiolkowskiJakub 
this is now urgent where we can get this moving?
I really need Pull Physical Panel

**Comment by IsakNaslundBh** [comment]
@michaldengusiak 
I am currently working through the framing elements. Once this is done, @ZiolkowskiJakub will update the code to enable the physical roof/floor/wall.

**Comment by FraserGreenroyd** [comment]
Discussion in BHoM call: This issue was partially completed in #315 but still needs work on:
 - Physical Wall
 - Physical Floor
 - Physical Roof

@ZiolkowskiJakub to perform the updates. Reassigned issue accordingly.

**Comment by michaldengusiak** [comment]
@ZiolkowskiJakub - full list with tick boxes for you
Pull:
- [ ] Wall
- [ ] Floor
- [ ] Roof
- [ ] Door
- [ ] Window
Push:
- [ ] Wall
- [ ] Floor
- [ ] Roof
- [ ] Door
- [ ] Window

**Comment by ZiolkowskiJakub** [comment]
Pull/Push workflow sketch for Analytical/Physical BHoM object:

Revit Analytical -> Structure Analytical **(Read Only)** if Revit Analytical does not exist then give warning and pull Physical then convert to Structure Analytical

Revit Analytical -> Environmental Analytical **(Read Only)** if Revit Analytical does not exist then give warning and pull Physical then convert to Environmental Analytical

Revit <-> Physical <-> Environmental Analytical **(Read/Write)**

Revit <-> Physical <-> Structure Analytical **(Read/Write)**

@rwemay @pawelbaran @al-fisher

**Comment by FraserGreenroyd** [comment]
Changing milestone as any feature functionality still required by this issue will now need to be in the 2.5 sprint.

**Comment by pawelbaran** [comment]
I am closing this one as it seem to be a compilation of smaller issues - please feel free to reopen in case you think it should remain open.
