### ISSUE TITLE
Revit_Toolkit: Provide Macro Test Folder and initial files

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/Revit_Toolkit#313]
[Operations : Provide Macro Test Folder and initial files for all interoperability Toolkits (#59)](https://github.com/BuroHappoldEngineering/Operations_Toolkit/issues/59)

**Comment by ZiolkowskiJakub** [comment]
Test Files for Environmental:
[Pull ](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=zra8mO&cid=16b0fa43%2Da8a4%2D45b8%2Db4e6%2Daf53369a09c2&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPull%2FEnvironment)
[Push](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=zra8mO&cid=16b0fa43%2Da8a4%2D45b8%2Db4e6%2Daf53369a09c2&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPush%2FEnvironment)
@michaldengusiak 

Test Files for Structural:
[Pull](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=zra8mO&cid=16b0fa43%2Da8a4%2D45b8%2Db4e6%2Daf53369a09c2&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPull%2FStructure)
[Push](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=zra8mO&cid=16b0fa43%2Da8a4%2D45b8%2Db4e6%2Daf53369a09c2&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPush%2FStructure)
@IsakNaslundBh

**Comment by ZiolkowskiJakub** [comment]
Related Structural Issue #261

**Comment by ZiolkowskiJakub** [comment]
Hi @michaldengusiak,

Can you please add Macro test files for Pull/Push?

Thank you in advance.

**Comment by michaldengusiak** [comment]
@ZiolkowskiJakub 
ok added Pull and Push including linking examples, simple and complex
