### ISSUE TITLE
Revit_Toolkit: Feature required to pull and push 'Line' category elements geometry.

### ISSUE THREAD

**Issue by nirbhay93** [BHoM/Revit_Toolkit#322]
Feature required to pull and push '**_Line_**' category elements geometry.

**Comment by ZiolkowskiJakub** [comment]
Hi @nirbhay93,

Can you please provide sample what you want to pull and save it here:
[PullPushLine](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue322-PullPushLine?csf=1&e=pnYGaf)

**Comment by nirbhay93** [comment]
Yes @ZiolkowskiJakub. Revit file, Grasshopper script and a screenshot are uploaded in the given folder.
Thanks!
