### ISSUE TITLE
Revit_Toolkit: How do we debug after new dll location change

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#327]
I can not attached debug to Rhino anymore or to revit...

**Comment by ZiolkowskiJakub** [comment]
Can you try this:
1. delete ALL build folders from your github folder
2. remove the BHoM folders in both dynamo packages
3. remove from &AppData%/BHoM/Assemblies
4. rebuild everything

Debug shall works as usual after this steps

**Comment by michaldengusiak** [comment]
ok now works perfectly, thanks
