### ISSUE TITLE
Revit_Toolkit: Issue with Pulling Detail Items

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#331]
issue with pulling detail items

![image](https://user-images.githubusercontent.com/26113670/60097510-72732180-974b-11e9-8e31-9870dfd5afa0.png)

[test file here](url)

**Comment by ZiolkowskiJakub** [comment]
Hi @michaldengusiak,

Can you test it again after full rebuild?

PS: link you provided for test file does not work for me.

**Comment by michaldengusiak** [comment]
@ZiolkowskiJakub  now works thanks
