### ISSUE TITLE
Revit_Toolkit: Pulling channels fails due to missing '!'

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Revit_Toolkit#332]

**Comment by ZiolkowskiJakub** [comment]
Hi @JosefTaylor ,

Can you please provide more details about the issue?

Can you save all test files here:
[Test Files](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue332-PullingChannelsFails?csf=1&e=Dt2z4m)

Thanks in advance.
