### ISSUE TITLE
Revit_Toolkit: Dimension name search lists yield erroneous results

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Revit_Toolkit#333]

**Comment by ZiolkowskiJakub** [comment]
Hi @JosefTaylor ,

Can you please provide more details about the issue?

Can you save all test files here:
[Test Files](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue333-DimensionNameSearchLists?csf=1&e=81ErH6)

Thanks in advance.

**Comment by JosefTaylor** [comment]
No idea if this is still an issue, or what the issue was. I'm sorry, world!
