### ISSUE TITLE
Revit_Toolkit: Ability to Query Rooms/Spaces for their Contained Objects

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Revit_Toolkit#342]
Add engine method for querying rooms/spaces for their contained objects

**Comment by travispotterBH** [comment]
@rboulton-BH I thought that this was built recently to achieve something similar. Is that true? https://github.com/BHoM/BHoM_Engine/blob/develop/Geometry_Engine/Query/IsContaining.cs

**Comment by vietle-bh** [comment]
We can fulfil this feature request by adapting/extending the Revit API method though.

**Comment by michal-pekacki** [comment]
@vietle-bh I agree, I have used this workflow in dynamo scripts on the projects and it worked fine with `IsPointInSpace` and `IsPointInRoom` method.

**Comment by pawelbaran** [comment]
> @vietle-bh I agree, I have used this workflow in dynamo scripts on the projects and it worked fine with `IsPointInSpace` and `IsPointInRoom` method.

Interesting, I remember the never ending discussion about this topic in Warsaw in the old days 😃 Glad to hear you've managed to make it work 👍 

In this case, should it be another request, `FilterByRoomRequest` or similar? Btw, what about the elements other than `FamilyInstances` @michal-pekacki?

**Comment by michal-pekacki** [comment]
For curve elements I used midpoints. I know this is not ideal as sometimes one element can be in more than one room, but in this case it met the needs.

**Comment by vietle-bh** [comment]
Can we also sample points along the location curve and get the room containing the most points?

**Comment by pawelbaran** [comment]
Yeah that could be an option. However, containment checks are quite heavy, so I would start from testing the performance - we would need to touch every element of given type, extract its 'control points' and check them against rooms. This makes me a bit concerned, taken that even filtering by parameter is already quite slow on large models...

**Comment by vietle-bh** [comment]
Looks like the below has resolved this issue. Please reopen if not.

https://github.com/BHoM/BHoM_Engine/pull/3203

**Comment by pawelbaran** [comment]
@vietle-bh are we sure we have an end to end workflow that allows finding elements contained in Revit spaces? The PR you've linked covers the BHoM side of it, but does it apply to the Revit workflows? @enarhi @michal-pekacki you should know best I believe?

I will reopen the issue until we confirm it really is sorted for the Revit workflows 👍

**Comment by michal-pekacki** [comment]
Currenly we have `IsInSpace(element, space)` method in Schematic_Tool repo based on API methods but it is private for internal use. It would be worth moving this to Revit_Toolkit for general use 👍

**Comment by vietle-bh** [comment]
Looks like this issue should have been created in BHoM_Engine. The issue description mentions "engine method" after all.

For Revit, we can just use any of the 4 API methods already available. They seem already convenient enough. Anyway, if we want to wrap them in a Revit_Toolkit as well then yes, let's keep this issue open 👍

**Comment by pawelbaran** [comment]
@michal-pekacki @enarhi now I am not sure... Do you think we have any further requirements in this concern on the Revit side?

**Comment by michal-pekacki** [comment]
I would close this since we already have a usable BHoM_Engine method (as @vietle-bh mentioned). If we need to improve or change it, another issue should be created.

**Comment by pawelbaran** [comment]
Oke, leaning towards predecessors ⬆️ and closing!

**Comment by enarhi** [comment]
Agree with the above for posterity's sake @pawelbaran!
