### ISSUE TITLE
Revit_Toolkit: Structure Panel Request Getting Additional ModelInstance Objects

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/Revit_Toolkit#356]
#### Description:

> Odd behaviour pulling `Structure.Elements.Panel` - getting additional `ModelInstance` object.
> ![image](https://user-images.githubusercontent.com/15924573/62273534-abcb3b00-b435-11e9-98f0-ff5704fdfe33.png)

@al-fisher this seems to be working fine for me, could not reproduce the issue. Do you have a test file where that issue occurs? BTW, is it related to this PR? It looks like an issue with STR analytical pull.

#### Test file(s):

[Test Files Folder](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-%23356-PullStructuralPanelGettingModelInstances?csf=1&e=ngLQVU)

_Originally posted by @pawelbaran in https://github.com/BHoM/Revit_Toolkit/pull/352#issuecomment-519832916_

**Comment by pawelbaran** [comment]
@al-fisher this is being pushed to the next milestone due to the lack of test files that replicate the issue - it would be great if you could upload something to the folder mentioned above.

**Comment by pawelbaran** [comment]
Closing this one as is likely to be fixed with 2.4 Beta - @al-fisher please reopen if the issue reoccurs.
