### ISSUE TITLE
Completely refactor Revit Requests

### ISSUE THREAD

**Issue by alelom** [BHoM/Revit_Toolkit#364]
#### Broken rules:

As discussed here: https://github.com/BHoM/BHoM_UI/issues/121#issuecomment-528822108

Requests in Revit are improperly implemented and cause compliance issues. Consequently the menu is not structured as it should and Requests are difficult to find.

#### Suggestions to restore compliance:

1. All Revit requests should not be of type `FilterRequest`. That is a misuse of the `FilterRequest` type. They must be their own implementation of IRequest. So, for example, the `SelectionFilterRequest`:
https://github.com/BHoM/Revit_Toolkit/blob/003156a5d23c23ad46c24336eda4db16e75a9125/Revit_Engine/Create/FilterRequests/SelectionFilterRequest.cs#L37-L44
must be rewritten as composed by two parts:
     - a new `BH.oM.Revit` -> `SelectionRequest` class
     - a `BH.Engine.Revit.Create` method that returns a new `SelectionRequest`, much like the code above but without the use of FilterRequest.

2. The previous point must be done for all Revit Requests until no FilterRequest is left.

Note that all Requests must live under the Revit namespace as specified in point 1, unlike the current location under the "Adapters.Revit" namespace:
https://github.com/BHoM/Revit_Toolkit/blob/003156a5d23c23ad46c24336eda4db16e75a9125/Revit_Engine/Create/FilterRequests/SelectionFilterRequest.cs#L31
the "Adapters" part is wrong as we are in an Engine part of the code. You can't have both `Engine` and `Adapter` in the namespace, only Engine is correct in this case. 

@adecler @al-fisher please correct me if wrong / see if I missed anything

**Comment by adecler** [comment]
Thanks @alelom ,

I would just add for clarity that everything that was stored inside the Equality dictionary now needs to be stored in its own property. This means you will likely have to create multiple IRequest classes. This also provides a better experience for the end user since the Request components will clearly indicate what inputs are expected. Check the GitHub toolkit if you need more examples of IRequest implementations.

**Comment by ZiolkowskiJakub** [comment]
Hi @alelom,

I am running couple of tests on implementation of `IRequest` and I wonder if you could answer one of my questions:

Revt_Toolkit implements `RevitUIAdapter` which inherits from `BHoMAdapter`. Currently, the overriden Read method  (`public virtual IEnumerable<IBHoMObject> Read(FilterRequest request)`) is used to pull objects via Adapter. 

As you can see it accept `FilterRequest` as input therefore I cannot use this method with `IRequest` implementation. The question is:

Which method should be used to pull object via Adapter after implementation of IRequest? Should it be 'Pull' method (`public virtual IEnumerable<object> Pull(IRequest request, Dictionary<string, object> config = null)`)? Is it fully implemented in BHoM?

**Comment by alelom** [comment]
Instead of overriding `Read(FilterRequest request)`, you should implement another `Read(IRequest request)`. Let's have a skype for further clarification

**Comment by ZiolkowskiJakub** [comment]
This issue has been parked after discussion with @alelom 

These BHoM Adapter issues have to be solved before:
[BHoM_Adapter Issue 149](https://github.com/BHoM/BHoM_Adapter/issues/149)
[BHoM_Adapter Issue 148](https://github.com/BHoM/BHoM_Adapter/issues/148)

**Comment by ZiolkowskiJakub** [comment]
Workaround suggested by @alelom :  

> Override the Pull and get it to call the Read(IRequest) method

**Comment by pawelbaran** [comment]
@alelom @IsakNaslundBh would you be fine with taking over this issue?

**Comment by alelom** [comment]
Hey @pawelbaran, I remember I had a go in trying to make things compliant here but took me a while just to get oriented. I will have another go on this as part of Adapter Refactoring 04, but I will definitely need some help, especially on the testing side.

**Comment by FraserGreenroyd** [comment]
@alelom you'll have all the support we can muster for testing, I think @pawelbaran is referring to writing the code to resolve the issue primarily :smile:

**Comment by pawelbaran** [comment]
@FraserGreenroyd is perfectly right - I am happy to support in testing and review, but would prefer the code to be written by someone with better understanding of the problem.
