### ISSUE TITLE
Prefix all warnings with Disciple/Namespace on pull Physical

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Revit_Toolkit#380]
#### Description:

The idea is to improve clarity of relevance of warnings for transdisciplinary workflows.

![image](https://user-images.githubusercontent.com/15924573/65683905-618dc100-e056-11e9-887c-a1439618103d.png)

Suggest prefixing warning on pull of physical objects from Revit such as:

``` C#
string aMessage = "Environment: Could not find Revit Thermal Asset for BH.oM.Environment Material Fragment.";
```

or similar.

**Comment by al-fisher** [comment]
This can be `Physical` itself if relevant to all or  
`Environment`
`Structure`
`MEP`
`Lighting` ...
any discipline/namespace going forward

**Comment by pawelbaran** [comment]
Closing this as it overlaps with #400.
