### ISSUE TITLE
Heal Space Location

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#386]
#### Description:

new to be `HealSpaceLocation `or `SetSpaceLocation `or `FixSpaceLocation `or `AdjustSpace` feel free to chose name
This method will modify existing `Space` with following steps
~Upper Limit (set next level above current Level)~
~Limit Offset = 0~
~Base Offset = 0~
- [ ] update Space location (will use Space Floor Geometry and Point in Region to get beautiful point)

outcome perfect and neat space in Revit

**Comment by rwemay** [comment]
Should we be writing modify methods inside Revit_Toolkit? This sounds like something to put in a toolkit that deals with manipulation/modification, unless it is specifically and only to ever operate on Revit spaces.

**Comment by michaldengusiak** [comment]
yes. good point -  this one is very specific to Revit only...as is irrelevant to anything outside Revit

**Comment by rwemay** [comment]
Ok! It sounded like something you might want/need outside of Revit, to 'fix' a space location/properties, in which case it could be written elsewhere as a BHoM method with converts/reference within Revit_Toolkit, but if only ever applicable in Revit makes sense to keep it contained.

**Comment by michaldengusiak** [comment]
ok I will document this for future referece

**Comment by pawelbaran** [comment]
@ZiolkowskiJakub @michaldengusiak @FraserGreenroyd is this issue still relevant?

**Comment by michaldengusiak** [comment]
Still needs solving

**Comment by pawelbaran** [comment]
@FraserGreenroyd I am making you the only assignee - please feel free to pass the issue to a relevant person in your team, I will not be able to resolve it.
