### ISSUE TITLE
Enable pushing pure geometry

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#408]
#### Description:
At the moment it is impossible to push pure geometry from BHoM to Revit. Would be good to allow this, even in a form of a non-editable in-place object, DirectShape or similar.

**Comment by ZiolkowskiJakub** [comment]
Hi @pawelbaran,

We cannot use in-place families in this case due to fact it is not supported by Revit API: [link](https://forums.autodesk.com/t5/revit-api-forum/family-in-place-api/td-p/7078982)
