### ISSUE TITLE
Set DampingRatio for IMaterialFragment in Revit 2020

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/Revit_Toolkit#415]
#### Parent issue(s) or Pull Request(s) causing the changes:

N/A

#### Description:

Revit 2020 does not support StructuralAsset.DampingRatio. Property has to be set from different source.

Method:
`private static IMaterialFragment Update(this IMaterialFragment materialFragment, StructuralAsset structuralAsset)`

Current version:

```
#if REVIT2020

#else
            double dampingRatio = structuralAsset.DampingRatio;
#endif
```

and then

```
#if REVIT2020

#else
            materialFragment.DampingRatio = dampingRatio;
#endif
```

#### Test file(s):

N/A

**Comment by pawelbaran** [comment]
Apparently the property disappeared from Revit at all. It does not exist neither in _StructuralAsset_ nor in _BuiltInParameters_.

2019:
- https://www.revitapidocs.com/2019/1ea2dc46-8ab9-3700-a19b-57229466fe44.htm
- https://www.revitapidocs.com/2019/fb011c91-be7e-f737-28c7-3f1e1917a0e0.htm

2020:
- https://www.revitapidocs.com/2020/1ea2dc46-8ab9-3700-a19b-57229466fe44.htm
- https://www.revitapidocs.com/2020/fb011c91-be7e-f737-28c7-3f1e1917a0e0.htm

Therefore, I assume the current code is OK - closing the issue.
