### ISSUE TITLE
Ensure default (debug and release) configurations build 

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Revit_Toolkit#416]
Following the recent close out of PR switching dependency on NuGets [here](https://github.com/BHoM/Revit_Toolkit/pull/414) default `debug` and `release` no longer compile.

Suggested fix is to simply align the default `debug` and `release` to one selected versioned config.

This is causing auto-installer builds on azure to fail. 
There is asymmetry between AppVeyor which only checks the specific hard coded configs on each repo and Azure which is in addition also building the available default `release`

Will raise issues to resolve differences in CI approach - however, think important that any default config must be buildable in any case.

**Comment by ZiolkowskiJakub** [comment]
Hi All, I had discussion about it with @IsakNaslundBh, I will update debug and release as you suggested however the question is default version of Revit we should use for `Debug` and `Release` configuration?

**Comment by IsakNaslundBh** [comment]
Hi @ZiolkowskiJakub , @al-fisher has fixed this already in here https://github.com/BHoM/Revit_Toolkit/pull/417, putting 2018 as default for now. We can ofc change this later if we want.
