### ISSUE TITLE
Allow pushing sloped floors

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#421]
#### Description:
Currently an attempt to push a sloped floor results in generating a horizontal one.

#### Test file(s):
GH test script is on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue421%2DAllowPushingSlopedFloors), can be run on any Revit model.

**Comment by jdarcyBHE** [comment]
It would be good if this could be prioritised for use on a current live project.

**Comment by pawelbaran** [comment]
Apologies @jdarcyBHE but I cannot get to this one due to critical, framework-related changes I am trying to push in this milestone. I will try to tackle it in the coming weeks, cannot tell when exactly though.

**Comment by jdarcyBHE** [comment]
Thanks for the update as long as it's on the radar for the near future that's ok.
