### ISSUE TITLE
Pull anchor point of viewport 

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/Revit_Toolkit#422]
Hi team,

I wonder if there is a way to pull anchor points of a viewport from a sheet?

A bit background of what we are trying to do - we (or architect) produce pdf from floor plan sheet and then we bring pdf into Rhino as reference. However, because sheets are created manually (which is difficult to automate since each project is different and need adjustment of view/hide setting), the floor plan of each level are not aligned. We would like to pull some geometry information from Revit to help moving pdfs to the correct location.

Information available:
- anchor point of pdfs
- architectural grids, which we can get min X gid and min Y grid to have a reference point of grid

Information needed:
- anchor point of viewport
- architectural location of the viewport anchor point, which we can calculate the relative location between the viewport anchor point and architectural grid 

This is only one possibility to import pdfs with correct location and scale. If there is any better way to do it, please let us know. Thanks.

**Comment by pawelbaran** [comment]
Hi @BingWangUS,

`Viewport` class has a property named `Location` that stores the information about viewports's location on sheet, isn't that what you are looking for?

**Comment by BingWangUS** [comment]
> Hi @BingWangUS,
> 
> `Viewport` class has a property named `Location` that stores the information about viewports's location on sheet, isn't that what you are looking for?

Thanks @pawelbaran for getting back to me. This was a request when working with @michaelhoehn to use Revit anchor point to import pdf drawing into Rhino at the correct location, which was part of a pdf import workflow. I'm not sure if the workflow is still active so not sure if the functionality is still needed. @michaelhoehn can you give an update if this is still needed?

**Comment by vietle-bh** [comment]
Hi @michaelhoehn , is this issue still relevant?

**Comment by michaelhoehn** [comment]
I'm closing this issue as the workflow has not been brought up again in many years. There was a functional prototype script that I can provide if needed, but as far as I'm aware this hasn't been needed since. Anyone can tag me again in a new issue if you'd like to further discuss.
