### ISSUE TITLE
Issue with pulling Spaces

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#423]
#### Description:

Environmental Engine method `aSpace.AddFragment(aOriginContextFragment)` has been chagned to not accept similar types 

![image](https://user-images.githubusercontent.com/26113670/67811266-49b1be80-fa94-11e9-8515-01e147831d08.png)

**Comment by FraserGreenroyd** [comment]
Following investigation kicked off by @BingWangUS and PR #424 it is identified that pulling spaces on their own from Revit models does not work owing to a confusion over the fragments.

The PR to fix this issue fixes @BingWangUS issue so we can get this merged, despite the original issue not making a lot of sense.
