### ISSUE TITLE
Revit_Toolkit: Ceiling Patterns

### ISSUE THREAD

**Issue by TheresaBrown** [BHoM/Revit_Toolkit#427]
#### Description:
Ability to pull the geometry of the ceiling patterns for lighting, diffuser, and sprinkler placement. Ceiling patterns are determined by material type (a drop down menu) within the linked architect's model.

![image](https://user-images.githubusercontent.com/57261582/68030948-f6588f80-fc90-11e9-8f36-9118aa46f4c4.png)

@FraserGreenroyd

**Comment by FraserGreenroyd** [comment]
Thanks @TheresaBrown - I've set up the assignments and milestone as discussed on the call :smile:

**Comment by pawelbaran** [comment]
@FraserGreenroyd is that seriously critical?

**Comment by FraserGreenroyd** [comment]
By the definition of the critical label, yes.
