### ISSUE TITLE
Revit_Toolkit: Pull shape geometry for IFramingElement if no location is available

### ISSUE THREAD

**Issue by rwemay** [BHoM/Revit_Toolkit#428]
#### Description:

Pulling framing elements gives null location property when there is no location curve (e.g. a mass based generic structural family). Would be good to pull the mesh/direct shape/geometry in the cases where the location property fails/isn't available. 

#### Test Script:

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Issues/Issue-428_Pull%20IFramingElement%20Edges?csf=1&e=Nvgy83

**Comment by ZiolkowskiJakub** [comment]
Hi @rwemay,

Have you looked on existing functionality described here:
[Pull Edges](https://github.com/BHoM/Revit_Toolkit/wiki/Pulling-Revit-Elements#pull-edges)


![image](https://user-images.githubusercontent.com/16777757/68155029-c800db80-ff40-11e9-86e7-f880a56677b8.png)

**Comment by rwemay** [comment]
Thanks @ZiolkowskiJakub , saw this. Ideally don't want to pull edges for everything - only the IFramingElements that are mass based/don't return a location. I guess the pull IFramingElement can refer to the edges method, and return a warning to say that's what's happened. By the way on warnings,

**Comment by rwemay** [comment]
@ZiolkowskiJakub , have added a test script/model - looks like the edges isn't working for this use-case/element anyway.

**Comment by rwemay** [comment]
@pawelbaran by way of an update on this, I've looked into this a bit more and it looks like in the test script, the convert edges is being called. I suspect this might be an issue of nested families actually, but need a bit more time to investigate. I also think any updates on this should tie in with geometry issues being raised - would be great to convert geometry based on what it is, in addition to edges (although will not suggest that holds up fix to this).

**Comment by pawelbaran** [comment]
@rwemay cleaning up the geometry converts is on my list - however, this will mainly be curves as the surfaces are a different layer of complexity (still not implemented in many cases). Therefore, I believe it would be fair to focus on getting the edge curves out of an object in the first iteration...

**Comment by rwemay** [comment]
👍

**Comment by pawelbaran** [comment]
@rwemay now, since we have a possibility to pull meshed geometry of an element, is it fair to close this issue?

I explained my stance in https://github.com/BHoM/Revit_Toolkit/issues/708 - in general, I would rather expect the user to pull the meshed geometry on  demand (pull framing -> filter ids without curve if they exist -> pull again with mesh).

Two issues I see with pulling meshes as a default behaviour:
- what if, for some reason (say, import from somewhere), all framing elements had no driving curves and even a minor pull would require meshing and conversion?
- returning meshed ootb will hide the problem from the user - 'I see it so it is fine', which I believe can be dangerous

Or am I getting confused? 🤯

**Comment by pawelbaran** [comment]
As explained in https://github.com/BHoM/Revit_Toolkit/issues/708#issuecomment-699975548, I believe the detailed decision about what to pull should lie on the user, I have also proposed a very simple script that helps to filter out and re-pull the `ModelInstances` incl. their representation. In my opinion that should conclude the discussion (at least for now 🙊).

I am closing this issue, but same as in #708, please feel free to reopen it in case you strongly believe the problem has not been resolved and development on the side of Revit_Toolkit is required. Thanks!
