### ISSUE TITLE
Revit_Toolkit: Donut-shaped floors lose the internal boundary on convert

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#429]
#### Description:

When converting a donut-shaped floor Revit -> BHoM -> Revit, the inner boundary gets lost.

#### Test file(s):

Test file uploaded to [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue429%2DDonutShapedFloorsLoseTheInternalBoundaryOnConvert).

#### Additional comments:
Possibly to be resolved in a larger wave of refactoring planned in 19Q4 and 20Q1.

**Comment by kThorsager** [comment]
Just saw this one, probably due to the same issue as in #620 where pulled holes are placed on the floor in a in-compliant way
