### ISSUE TITLE
Revit_Toolkit: Resolve compilation warnings

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Revit_Toolkit#433]
**By 30th November please**

#### Broken rules:
Compiler warnings occur when compiling the toolkit.

#### Suggestions to restore compliance:
Ensure code compiles without any warnings.

**Comment by pawelbaran** [comment]
Hey,

I changed the issue name since we have warnings to be sorted out on the UI level (#409).

**Comment by FraserGreenroyd** [comment]
Following the work done on the #444 branch (encompassing #438 and #472 ) a lot of the warnings have been resolved. There now resides 10 warnings, which focus on CPU architecture rather than code to be resolved.

**Comment by FraserGreenroyd** [comment]
This was fixed in #474 with outstanding warnings being accepted pending further investigation.
