### ISSUE TITLE
Revit_Toolkit: Remove 'a' and 'p' prefixes in variable names

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#438]
#### Description:

Variables in many parts of Revit_Toolkit have prefixes _a_ (local) and _p_ (private) - would be worth to clean up the code.

**Comment by FraserGreenroyd** [comment]
I am starting this on my branch `Revit_Toolkit-#444-Tidy` just an FYI!

**Comment by pawelbaran** [comment]
Possibly you could tackle #472 in one batch?

**Comment by FraserGreenroyd** [comment]
I didn't see #472 and have already been doing it as part of tidying up in this issue so yeah, I'll tackle #472 in the same branch :smile:
