### ISSUE TITLE
Revit_Toolkit: Make all BH.UI.Revit.Engine internal methods public

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#440]
#### Description:
It would be good to change all public methods in `BH.UI.Revit.Engine` to internal so that there is one pattern across the whole project.

**Comment by pawelbaran** [comment]
Afterthought: I would actually make `public` all methods that are not specific solely to the assembly, so that they could be reused in other projects.

@rwemay @al-fisher

**Comment by al-fisher** [comment]
Agreed. In general across the BHoM avoiding `internal` and simply making `public` where possible and where can be useful across projects - and then simply setting other methods `private` where they are only locally relevant.
