### ISSUE TITLE
Revit_Toolkit: Create WarningSwallower class that will be carried by PushSettings

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#449]
#### Description:
Create a `BH.oM.Adapters.Revit.Generic.WarningSwallower` class to be carried by `PushSettings` and converted into a correspondent `IFailuresPreprocessor` to handle Revit warnings and errors.

As a follow up, private class `WarningSwallower` used in `BH.UI.Revit.Engine.Query.GetEnergyAnalysisModel` should be replaced.

`BH.UI.Revit.Adapter.RevitUIAdapter.ControlledApplication_FailuresProcessing` could possibly be unified too.

**Comment by FraserGreenroyd** [comment]
@pawelbaran we have a week to implement this on the 3.0 MVP timescale, do you think we'll get this done next week? I'm thinking you might be better placed to do it because you know the `WarningSwallower` better than I do, but I'm happy to take an attempt :smile:

**Comment by pawelbaran** [comment]
Yeah, still aiming to get this done next week - Revit side should be rather easy, I am more concerned about wrapping it neatly on the BHoM side. TBC!

**Comment by FraserGreenroyd** [comment]
Ok SGTM - are you happy with taking ownership of it then? :smile:

**Comment by pawelbaran** [comment]
This has been covered in 3.1 with `PushConfig.SuppressFailureMessages`
