### ISSUE TITLE
Revit_Toolkit: Remove ConvertUnits?

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#450]
Currently `PushSettings` and `PullSettings` carry `ConvertUnits` property. As discussed recently, it might be desirable to force conversion by removing the above as some concepts in Revit are Imperial and some SI.

Would be good to confirm that before actioning @al-fisher @rwemay @IsakNaslundBh @FraserGreenroyd @JosefTaylor @enarhi @kayleighhoude

**Comment by JosefTaylor** [comment]
I'd like to bring more toolkits into line by forcing SI units for all- currently some toolkits aren't because the Localization_Engine isn't finished, and these packages have some pretty funny units going on.

I don't see a point in letting users avoid converting units- it seems like a recipe for confusion (my non-programming colleagues in the US will disagree, I'm sure they'd like to see their results in imperial, but I know how complicated that will make things)

**Comment by IsakNaslundBh** [comment]
I would confirm. All BHoM needs to be in SI, at least on the oM/engine level. UI could be different once we get localisation toolkit etc in place, but oM just needs to follow a single consistent convention so should _always_ be converted to SI.

Even more sure now that @JosefTaylor has agreed as well.

**Comment by pawelbaran** [comment]
OK, in this case I am happy to go through the whole repo and squash `ConvertUnits` wherever they appear. However, this will influence some half of the Revit_Toolkit - the question is should we deprecate every item that changes (slow) or is it fine if I just refactor all without looking back (quick)? @al-fisher @rwemay @adecler

**Comment by adecler** [comment]
@pawelbaran , backward compatibility for methods is coming soon and allows you to change methods on the spot without keeping a deprecated version. Backward is already available for objects. Both need to add conversion information in the Versioning_Toolkit though and that repo is heavily being redefined and worked on at the moment. 

So TL;DR, you can just change methods and objects locally as long as you record the change in the versioning toolkit. But you will have to wait a bit longer before you can do that.

**Comment by pawelbaran** [comment]
In this case I guess it would be best to hold on with this issue until the Versioning_Toolkit is stable.
