### ISSUE TITLE
Revit_Toolkit: Implement converts from Revit surfaces to BHoM

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#454]
#### Description:
At the moment conversion of surfaces is possible only in one direction: from BHoM to Revit. The opposite needs to be implemented.

**Comment by tiagogrossi** [comment]
@pawelbaran I've explored this further and got a working prototype, may need to adjust some details though:

- Implemented a new item in 'RevitPullConfig' as 'PullSurfaces' to expose surfaces.

- Added to 'Read' functionality the ability to read 'Surfaces'.

- Created method 'Surfaces' from above in 'Engine_Revit_UI.Query'

- Exposed in 'FromRevit' two new items as 'Surface' and 'SurfaceList' to be used in 'Surfaces' above.

- Only 'PlanarSurface' exposed at the moment.

Any thoughts? Shall I create a branch to test and discuss?

**Comment by pawelbaran** [comment]
I would say go for it and create PR 👍 You can label it as _draft_ if you feel it needs more work - happy to support you in that!
