### ISSUE TITLE
Revit_Toolkit: UpdateBuildingElementTypeByCustomData is a temporary fix

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#461]
#### Description:
Following the code comment: `BH.UI.Revit.Engine.Query.UpdateBuildingElementTypeByCustomData` method is a temp fix - should be resolved.

**Comment by FraserGreenroyd** [comment]
How long does it have to stay before we no longer consider it temporary? :wink:

**Comment by pawelbaran** [comment]
Owell. It might take a bit, taken into account that:
- the method does not reference Revit API
- the method seems to fall not into `Query`, but `Modify`
- the method is explicitly commented as temp fix

🐒

**Comment by pawelbaran** [comment]
@FraserGreenroyd what is the chance your team could tackle this one in 3.2?

**Comment by FraserGreenroyd** [comment]
Yeah go on then. I'll give it a try 😆 

I'm hoping to do some good Revit stuff this milestone with my gang, so can be assigned the milestone.

Though, I like this quote which becomes more apt day by day:

> How long does it have to stay before we no longer consider it temporary? :wink:

**Comment by FraserGreenroyd** [comment]
Have reviewed this, and it turns out the `temporary` comment is actually wrong. But it is using some of the original `SAM` workflows.

@kayleighhoude @rboulton-BH could we have a get together to discuss this issue ASAP along with any other key players as appropriate?
