### ISSUE TITLE
Revit_Toolkit: Hardcoded values in GetEnergyAnalysisModel to be moved to Fragments

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#466]
#### Description:
I have just spotted that there is a hardcoded parameter in `BH.UI.Revit.Engine.Query.GetEnergyAnalysisModel` method:
https://github.com/BHoM/Revit_Toolkit/blob/7e9d05b6ee18f3c1e53db5b28b93fb880252be0f/Engine_Revit_UI/Query/GetEnergyAnalysisModel.cs#L80

Shouldn't it be a setting?

**Comment by FraserGreenroyd** [comment]
Yes I believe it should. Where do you reckon we should put it?

**Comment by pawelbaran** [comment]
Looks like currently we do not have space for discipline-specific settings: after a chat with @FraserGreenroyd we came up with an idea of storing these in `Fragments` - to be prototyped in 3.1.

**Comment by FraserGreenroyd** [comment]
@pawelbaran now we can do discipline specific settings, do we still want to do this in a fragment?

**Comment by pawelbaran** [comment]
What do you mean by discipline-specific settings?

**Comment by FraserGreenroyd** [comment]
`ProgramData/BHoM/Settings` allows us to set up settings as needed - we could add discipline specific settings there for Revit on install, thus do we still want to do a fragment? Happy to do a fragment but thought I'd double check!

**Comment by pawelbaran** [comment]
Hmm good point. If the value is very unlikely to change, then it should make a lot of sense 👍

**Comment by FraserGreenroyd** [comment]
I don't see the value as likely to change, it hasn't needed to change in the last year! A fragment would be hard to set up within the framework for something like this, while a settings component would work well I think?

**Comment by pawelbaran** [comment]
Yeah, agreed. The `Fragment` I thought of could be attached to either `RevitSettings` or `ActionConfig`. Would that make any sense @IsakLarbornBH @alelom?

**Comment by FraserGreenroyd** [comment]
Did you mean @IsakNaslundBh ?

**Comment by pawelbaran** [comment]
Of course not, why? 😉 

Welcome onboard @IsakLarbornBH!

**Comment by IsakNaslundBh** [comment]
either as a fragement, or, I think could be ok to have a discipline config primary property on the Revit setting/configs, such as some EnvorinmentSettings or similar.

But fine with it being attached as a fragment as well.

**Comment by pawelbaran** [comment]
I believe Fragments can be more flexible than properties (what if we start having LCA settings etc.?). But in this case that does not matter, a settings file sounds good.

**Comment by FraserGreenroyd** [comment]
@pawelbaran shall we pick this up at some point 🥃 maybe with @vietle-bh to assist? Or maybe we now remove the code entirely - the file no longer exists as far as I can see so maybe we already refactored it out?

**Comment by pawelbaran** [comment]
It is still there @FraserGreenroyd 
https://github.com/BHoM/Revit_Toolkit/blob/3e63d9ac9e81fe4978aa68c424d03d39fbce3e20/Revit_Core_Engine/Convert/Environment/FromRevit/EnergyAnalysisModel.cs#L88

It looks like quite a bit of effort to remove this value though - not sure if worth our time atm...

**Comment by FraserGreenroyd** [comment]
I agree with it not being worth much time, just dislike seeing it on my todo list when I do periodic reviews. Ho hum - we can revisit in another 12-18 months when I next see it 😉 (if anyone else wants to pick this up though, please feel free!)
