### ISSUE TITLE
Revit_Toolkit: Unable to Push Nurbs based FramingElements to Revit

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Revit_Toolkit#473]
#### Description:

Currently unable to push a Beam with a NurbsCurve as location to revit.

A check for Length of the curve causes the convert to crash:

![image](https://user-images.githubusercontent.com/22005920/69544112-5809d200-0f8f-11ea-8c91-1ffe4fb67756.png)

Need to be more careful when dealing with nurbs as quite a few core methods such as length are missing in the Engine.

Know that Revit can not handle double curved nurbs and curves with to steep curvature, but should be able to handle the general case.

#### How to replicate:

Create a Beam object with a NurbsCurve and try to push it to revit.

#### Expected behaviour:

For Nrubs baed framing to be pushable to Revit

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/_Macro/Push/Physical?csf=1&e=XLP6Ly

**Comment by pawelbaran** [comment]
One-liner (caused by me) to be fixed before 3.0 release.
