### ISSUE TITLE
Revit_Toolkit: BH.UI.Revit.Engine.Convert.ToRevitElement(oM.Environment.Elements.Panel) should be deleted

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#477]
#### Description:
Pushing analytical objects is not allowed any more - the method is useless.

Same with:
- `BH.UI.Revit.Engine.Convert.ToRevitCompoundStructureLayer(oM.Physical.Constructions.Construction)`

**Comment by FraserGreenroyd** [comment]
> * `BH.UI.Revit.Engine.Convert.ToRevitCompoundStructureLayer(oM.Physical.Constructions.Construction)`

That isn't an analytical object though - that's a Physical Construction?

**Comment by pawelbaran** [comment]
Aye, good point! This, however, is not being used any more - panel property converts have been unified under `BH.UI.Revit.Engine.Convert.ToRevitHostObjAttributes`. So I would still opt for removing the legacy.

**Comment by FraserGreenroyd** [comment]
Ah ok that makes more sense :smile:
