### ISSUE TITLE
Revit_Toolkit: Refactor MapSettings

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#482]
#### Description:
Current implementation of parameter mapping using `MapSettings` is not fully functional: it is quite limited + used only in few cases (an in many not). It would be good to implement it as follows:
- create an external file (.json?) that would contain information which BHoM properties should be coupled with which Revit parameters etc.
- create a method that loads the above file as well as other files that contain project/user specific data in same format

This is likely to supersede #256, #258, #451.

**Comment by rwemay** [comment]
I wonder if we explore the DataTable class for this? Maybe a convenient way to store/retrieve mapping.

**Comment by pawelbaran** [comment]
Can be - for me they key aspect is to make it easily accessible for the end user, file format is rather less of my concern ;-)

**Comment by rwemay** [comment]
Right - yep agree and I think is why I'm suggesting thing about format a bit to make as easy as possible for users. Would be good to define a couple of workflows to define mapping. I'd say Excel is naturally one of the easiest UI's to use to review/define a mapping table, so making it easy for someone to create through that would be great.
