### ISSUE TITLE
Revit_Toolkit: Add warning when a structural framing element or bar location/centreline is unavailable

### ISSUE THREAD

**Issue by rwemay** [BHoM/Revit_Toolkit#489]
#### Description:
At the moment if a structural framing element is pulled that doesn't have a centreline (e.g. custom families like seating bowl rakers) then no centreline or location line is provided. It's up to the user to sift the null locations, but at the moment there's no warning.

**Comment by pawelbaran** [comment]
To be resolved as a part of #400
