### ISSUE TITLE
Revit_Toolkit: Pull Curtain Wall Mullions

### ISSUE THREAD

**Issue by rboulton-BH** [BHoM/Revit_Toolkit#494]
#### Description:
Have a Revit model where the shading elements are drawn as curtain wall mullions. Have tried to pull these using selection filter request but they come in as Revit ModelInstance with only a single point as the location and no other geometry. I would like to pull these preferably as BHoM objects with full outline geometry.

**Comment by rwemay** [comment]
Have you tried setting the 'pull edges' on the filter request? This in theory, should pull all the edge geometry.

**Comment by rboulton-BH** [comment]
Yes I think so, at least I tried this:
![image](https://user-images.githubusercontent.com/26925641/71821107-22c1cb00-3089-11ea-85ff-a0dd20c5345d.png)
But as you can see it doesn't seem to pull anything at all so I think I might be doing something wrong. Tried using both Environment and Structural Edge types. I have the 3.0 beta installed...

**Comment by rwemay** [comment]
Sorry, I meant the one just below - rather than pulling edges as a type, there's a modification you can make to the FilterRequest itself before plugging into Pull to SetPullEdges. I think this is one that's up for refactoring to make it easier to find/specify to pull geometry as necessary. 

![image](https://user-images.githubusercontent.com/15233608/71821579-6537d780-308a-11ea-8426-c3e390838a05.png)

**Comment by rboulton-BH** [comment]
Ahh nice, yeah that's worked now. Took a while to figure out that the edge geometry was hidden away in CustomData but that's definitely given me a workaround, cheers!
![image](https://user-images.githubusercontent.com/26925641/71826647-4b9c8d00-3096-11ea-808b-1ec066cf8641.png)

**Comment by rwemay** [comment]
Sorry! Great that it worked - definitely some improvements on usability/where the data gets stored etc.

**Comment by pawelbaran** [comment]
Before we close, @rboulton-BH did you try to pull curtain walls? Did it work correctly? I remember having some issues but cannot recall what was wrong - maybe you could help?

**Comment by rboulton-BH** [comment]
Sorry for the delay on this. It nearly works very nicely but not quite 100%.

If the mullions are connected to an adjacent element then the edges at the connection are missing:
![image](https://user-images.githubusercontent.com/26925641/73188025-2d1c3580-411a-11ea-967d-00b8f6140cbc.png)

For elements connected top and bottom then the edges aren't connected at all.
![image](https://user-images.githubusercontent.com/26925641/73188495-dd8a3980-411a-11ea-9065-d2b14978d921.png)

This means to create BHoM Panels to use as shading elements there is some geometry post-processing required. Do you know of any way around this or have any suggestions of how to do the post-processing best?

**Comment by rwemay** [comment]
This is probably to do with Revit joins/geometry output. Might not be a quick one to solve. You could infill the geometry in Grasshopper - filter the geometry to lines, and process these into panels by creating polylines or lofting the lines. If you internalise the geometry to a script an email it to me I can take a look if you like.

**Comment by pawelbaran** [comment]
Yeah, agreed with @rwemay, this one is probably caused by the way in which Revit handles topology. I like Grasshopper postproc as an interim solution, although I think we should implement something more structured in long term!

**Comment by rboulton-BH** [comment]
Great, this is what I was thinking as well. I have already been testing some postproc options in GH and spoken to @kayleighhoude about it so will share to all for feedback. @pawelbaran, do you want me to leave this issue open to keep on the to-do list or close it and open another one specifically for the Revit topology problem?

**Comment by FraserGreenroyd** [comment]
I'd keep this issue open @rboulton-BH as it captures the discussion that reaches the development decision until a proper revit fix can be done

**Comment by pawelbaran** [comment]
Agreed with @FraserGreenroyd, I would keep this issue open as a self-reminder

**Comment by pawelbaran** [comment]
I am handing this over to @enarhi - could you please share your thoughts on that topic? Is pulling curtain wall mullions on your radar?
