### ISSUE TITLE
Revit_Toolkit: Compatibile with Rhino 7 WIP - Rhino.Inside

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#496]
Happy New Year team  :)

I guess I am a bit ahead but I guess will be worth logging it. 
BHoM Revit 2020.2 is not compatible with Rhino.Inside
I ran a test and the current BHoM is not compatible with `Rhino.Inside`.
There is a conflict. I know that it is an issue with Revit because when I remove `BHoM Revit Addin`. It worked fine. I logged the same issue with Rhino. 

#### Description:

![image](https://user-images.githubusercontent.com/26113670/72209829-c4db1c00-34aa-11ea-9a23-de278fe6b075.png)

**Comment by epignatelli** [comment]
Hey @michaldengusiak , happy new year.

The description is a bit confusing.

What is the actual issue here? That the BHoM is not compatible with Rhino.Inside or that Revit 2020 is not?

**Comment by michaldengusiak** [comment]
@epignatelli ,
Yes, let me explain. BHoM is made of dozens of connected toolkits. 
I first thought it is BHoM overall,  but then started test each toolkit and noticed that Revit_Toolkit is causing conflict. I was testing this using Revit 2020.2.  So when I remove it, it works with Rhino.Inside. I hope this is clear now. Let me know if you need anything more.

**Comment by epignatelli** [comment]
Thanks @michaldengusiak! 

I am not sure, though, if there is anything we can do about it. That seems Autodesk/McNeel problem to me.
In case you find a solution, do let me know, we'll pin the issue up.

@pawelbaran I think that if there is nothing we can do we can close this issue for the moment?

**Comment by epignatelli** [comment]
@michaldengusiak In the meanwhile, I wasn't able to find the related issue in the Rhino.Inside repo, would you mind linking it in here? It'll help keep track of the progresses.

**Comment by pawelbaran** [comment]
Hmm hard to tell without debugging. Since it is Rhino.Inside crashing, the problem occurs on its side and needs to be tracked there (ideally by McNeel guys). Happy to work on resolving this once we know what causes Rhino.Inside to crash.

@epignatelli I would leave the issue open for reference and as a self-reminder.

**Comment by al-fisher** [comment]
Thanks all. Have tested my end for both Revit 2020.2 and 2018.3 - and BHoM Revit Adapter from within Rhino Inside all seems to be working as expected! 

### Pulling BHoM Grids using RhinoInside Revit 2020
![image](https://user-images.githubusercontent.com/15924573/72435396-e59abe80-3795-11ea-9908-51df243149aa.png)

### Pulling BHoM FramingElements using RhinoInside Revit 2020
![image](https://user-images.githubusercontent.com/15924573/72435402-e895af00-3795-11ea-9281-dd457467076a.png)

### Pulling BHoM Grids using RhinoInside Revit 2018
![image](https://user-images.githubusercontent.com/15924573/72435409-ec293600-3795-11ea-99cc-0e4af0de0a51.png)


@pawelbaran @epignatelli @michaldengusiak

**Comment by al-fisher** [comment]
@michaldengusiak - not sure what issue you were experiencing with that specific pop up showing Grasshopper failed to load? Can't recreate here.

As an aside I am getting this pop up 
![image](https://user-images.githubusercontent.com/15924573/72435725-a751cf00-3796-11ea-919d-9be150e12403.png)


And there are some funny behaviours with GH not detecting keystrokes when run as RhinoInside.

**Comment by michaldengusiak** [comment]
@al-fisher 
thanks for testing, on your side...
I have BHoM from today morning - masters... I am using Revit 2020.2 and Rhino
all is working now :) Huuurey

I also got the same opening error, I will try to talk about this during my time in Barcelona next week :) 
![image](https://user-images.githubusercontent.com/26113670/72752329-d498e580-3bb9-11ea-9dc7-b2783a4b74a2.png)

**Comment by al-fisher** [comment]
Great stuff! No problem! 👍 
Oh yes - let us know how get on with the guys in Barcelona 😄 Have fun!
