### ISSUE TITLE
Revit_Toolkit: Revit Parameters with "." Cause Errors

### ISSUE THREAD

**Issue by enarhi** [BHoM/Revit_Toolkit#499]
#### Describe the documentation issue:
- Due to BHoM standards parameters with "." cause issues, as GetProperty and Explode search for InnerProps when a property input contains "."

#### What is missing/incorrect?
- Documentation should mention that Revit parameter names should not contain "." if avoidable. We could also provide a string replacement method for parameters that do contain ".", but I will leave that up to discussion as it could impede round tripping back into Revit params later.

**Comment by rwemay** [comment]
Hopefully a fringe case?! I think a string replacement method/convention is the right approach.

**Comment by pawelbaran** [comment]
I will have a look into this, not sure if the issue occurs on conversion or maybe later, when the objects get treated by Reflection. Possibly this could be fixed rather than prohibited.

**Comment by enarhi** [comment]
@pawelbaran FYI this is causing further issues with downstream workflows when the parameters with "." exist in custom data of the object. One such example is serialization issues that leads to push to Mongo failing for any objects with "." in a property name.

**Comment by enarhi** [comment]
@pawelbaran this is causing downstream issues with the custom data properties created with ".". Suggest we move to high priority for the bug fix sprint next week as it is an easy fix that otherwise causes a lot of workflow issues.

**Comment by pawelbaran** [comment]
Hi @enarhi, https://github.com/BHoM/Revit_Toolkit/pull/751 introduces a new approach to handling parameters on pull (and push). Instead of copying them over to `CustomData`, they will be stored in `RevitPulledParameters` fragment as a collection of objects of type `RevitParameter`. I belive this will resolve this issue - am I correct?

**Comment by pawelbaran** [comment]
I am closing this one as resolved by #751 - please feel free to reopen if the issue reoccurs.
