### ISSUE TITLE
Revit_Toolkit: Clean up namespace/assembly names

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#517]
#### Description: 
Assemblies and namespaces sitting in Revit_UI folder to be reshuffled in order to make them more informative. My proposal (discussed to some extent with @al-fisher and @IsakNaslundBh) presented below.

**Project renaming:**
- _Revit_UI_ - to be renamed to _Revit_Listener_ as it is not the entire UI, just listener
- _Engine_Revit_UI_ - to be renamed to _RevitAPI_Engine_ (will allow exposing it in the UIs that work in Revit context)
- _Adapter_Revit_UI_ - to be renamed to _Revit_Adapter_Plugin_ to highlight that it sits on the Revit side (but is not UI)
- projects to be taken out of the _Revit_UI_ folder and placed on the same level as all others

**Namespace renaming:**
- `BH.UI.Revit` - to be renamed to `BH.UI.Revit.Listener`
- `BH.Adapter.Revit` - to stay untouched
- `BH.UI.Revit.Adapter` - to be renamed to `BH.Adapter.Revit.Plugin`
- `BH.oM.Adapters.Revit` - to be renamed to `BH.oM.External.Revit` 
- `BH.Engine.Adapters.Revit` - to be renamed to `BH.Engine.External.Revit`
- `BH.UI.Revit.Engine` - to be renamed to `BH.Engine.External.RevitAPI`
- `BH.oM.Adapters.Revit.Interface` - _Interface_ suffix to be removed, aligned as above

**Class renaming:**
- `RevitUIAdapter` - to be renamed to `RevitAdapterPlugin`

**Folder and file renaming:**
- folder _AdapterActions_ in Revit_UI to be renamed to _EventHandlers_
- _Push.cs_ file in the above folder to be renamed to _PushEvent.cs_
- _Pull.cs_ file in the above folder to be renamed to _PullEvent.cs_

What do you guys think? Any big no from anyone?

**Comment by pawelbaran** [comment]
I updated the content of this issue following the discussion in #385 - @adecler @alelom @al-fisher could you please have a look and flag up if there is any inconsistency in here? If not, I will action this in the current milestone.

**Comment by alelom** [comment]
Great to see a good summary like this! 
Agree 100%:
- The renamings proposed here would be highly beneficial for general understanding, compliance and tidy up.
- Great idea about the `EventHandlers` / `AdapterAction` change.
- Agree with everything else too.

**Comment by adecler** [comment]
I agree that the current project names and namespaces need to be improved. But I am not sure I like the proposed solution as it is not compliant. For example, a project should always end with either _oM_, _Engine_, _Adapter_, or _UI_. This is not just to make it easier for people to find their way around the code structure but also to enable automated processes. 

As always, Revit is a more complicated beast so it might be worth having a proper meeting around this to see if (and how) we need to extend our conventions or if we can obtain clarity with the existing one.

**Comment by pawelbaran** [comment]
Bumping to 3.2 due to [BHoM_UI #223](https://github.com/BHoM/BHoM_UI/issues/223)
