### ISSUE TITLE
Revit_Toolkit: Push of Types Results in Deletion of Associated Types/Elements

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Revit_Toolkit#522]
#### Description:
When pushing objects (particularly object types) the instances as well as the types are deleted

![image](https://user-images.githubusercontent.com/34316256/74046675-f9080680-499c-11ea-9ca4-f6d228218261.png)

**Comment by pawelbaran** [comment]
I am closing this one and moving the discussion to #546 - will try to tackle it in the current milestone. @kayleighhoude please feel free to reopen in case you believe that this should be separate from #546
