### ISSUE TITLE
Revit_Toolkit: Disallow conversion of Geometry objects to Environment.Panels

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#531]
#### Description:
Atm [Autodesk.Revit.DB.PlanarFace](https://www.revitapidocs.com/2020/e5f08848-bd35-4b17-ac7b-ae39fd817d6d.htm) can be converted to `BH.oM.Environment.Panel`. This should not be allowed as `PlanarFace` is a purely geometrical entity and does not inherit from `Autodesk.Revit.DB.Element` (therefore does not have ElementId etc.).

**Edit:** This should include removal of `BH.UI.Revit.Engine.Query.Panels(GeometryElement)` and `BH.UI.Revit.Engine.Query.Panels(GeometryElement)`

**Comment by FraserGreenroyd** [comment]
Why not? We don't need to have an ElementId for the panel to exist - the geometry is the most important part and any openings, so why can't we have a PlanarFace conversion? 😕

**Comment by pawelbaran** [comment]
The faces as such do not exist in Revit models according to my knowledge: they always belong to a surface, which belongs to an element. And what we should convert is an element: then we can match it by its `ElementId`, copy parameters, query its layers etc.

This sounds very much like a shortcut to get something working in SAM at any cost tbh.

**Comment by FraserGreenroyd** [comment]
> The faces as such do not exist in Revit models according to my knowledge: they always belong to a surface, which belongs to an element. And what we should convert is an element: then we can match it by its `ElementId`, copy parameters, query its layers etc.

Ok makes more sense to me, let's do it then
