### ISSUE TITLE
Revit_Toolkit: ToBHoMObjects(ProjectInfo) method is incompliant

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#537]
#### Broken rules:

- File name is unrelated to method name
- There are multiple hard-coded parameter names that should be migrated to `MapSettings`

**Comment by FraserGreenroyd** [comment]
> * There are multiple hard-coded parameter names that should be migrated to `MapSettings`

I'm not seeing them, can you point some out to me? 😖

**Comment by pawelbaran** [comment]
Sorry, not parameter names but CustomData names, my bad. I meant the lines below:
https://github.com/BHoM/Revit_Toolkit/blob/4f2a1b3522b110ebe4b9626c3513c155fc3dc7a4/Engine_Revit_UI/Convert/Environment/ToBHoM/Building.cs#L107-L114

Is that something we want to have hardcoded inside the method or should it be taken from an external source (probably not `MapSettings`, but the assembly that makes use of these values)?

**Comment by FraserGreenroyd** [comment]
Ah so you mean the custom data keys? I'm happy with those being hard coded that way for now, they are what makes most sense for the values when exploding the building, but I think some properties can go into a fragment now. I'll investigate and update the PR as appropriate.
