### ISSUE TITLE
Read works per element, Create takes list of objects

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#561]
#### Description:

Currently the private side of `Read` method works per element, while private side of `Create` takes `List<IBHoMObject>` as an input. Would be good to unify it. I guess this is something up to toolkit developer how to shape it best, but thoughts/suggestions would be more than welcome @alelom @IsakNaslundBh.

**Comment by pawelbaran** [comment]
Follow-up to the conversation with @alelom,  there is a few items that should happen in order to align with other toolkits and make the API more consistent:
- `Create(IEnumerable<IBHoMObject> objects, Document document, RevitSettings settings)` and 
`IToRevit(this IBHoMObject obj, Document document, RevitSettings settings = null, Dictionary<Guid, List<int>> refObjects = null)` method should be merged into `ICreate<T>(IEnumerable<T> objects, ActionConfig actionConfig = null)`
- all `ToRevit` methods should be renamed to `Create` as they not only convert BHoM -> Revit, but they also (or rather mainly) generate an element in the Revit document

@FraserGreenroyd could you please have a look and confirm you agree with that?

**Comment by FraserGreenroyd** [comment]
> * all `ToRevit` methods should be renamed to `Create` as they not only convert BHoM -> Revit, but they also (or rather mainly) generate an element in the Revit document

I'm not sure I agree with this - are they taking BHoM inputs (either Revit_oM objects like ModelInstance) or similar? If so, they should be `Convert` as they are converting from BHoM to the external software.

If they are just `Creating`, then what are they creating? Why are we creating non-BHoM objects in BHoM UIs would be my question there?

More than happy with the first part though.

**Comment by pawelbaran** [comment]
Hmmm, `ToRevit` methods neither only _Convert_ nor _Create_ - they do both, and these two functionalities cannot be split due to the way in which RevitAPI works (one cannot have an element that does not exist in the document). @alelom and me agreed that creation is superior to conversion as it changes the external software document. Is that a convincing explanation? 🙊

**Comment by pawelbaran** [comment]
> Not overly, because it's not creating a BHoM object. The Create methods are for creating BHoM objects within UIs and within toolkits, not external objects. 

Well, this stands very much in opposition to what @alelom has said plus what is implemented e.g. in Robot_Toolkit - @alelom @IsakNaslundBh could you please share your opinion on that? I am on _whatever works_ position with this regard, just want to do it as it should be done.

**Comment by alelom** [comment]
As clarified with @FraserGreenroyd the disagreement seemed to have originated from a misunderstanding: the Create methods we're talking about are the Adapter CRUD/Create methods, not the Engine.Create ones.

**Comment by FraserGreenroyd** [comment]
What @alelom said - I'm now in agreement with him on this after a skype chat

**Comment by alelom** [comment]
Given that we all agree, can we close this `question` issue?

**Comment by pawelbaran** [comment]
Please leave it open, I am just working on this one ATM - will update later today.

**Comment by alelom** [comment]
I'm just saying, since this seems to have been converted to an actual action, closing this `question` issue would signify the agreeement. You can open another `compliance` one for you to action what we agreed upon if you wish. This would remove the issue from me and Fraser backlog of open issues.

**Comment by al-fisher** [comment]
If the actions are now clear - you can also always just take the `question` label off the issue once agreement is found

**Comment by pawelbaran** [comment]
Actually this thread requires an update after our last week's discussion with @alelom:
-  `ToRevit` methods sit in the Engine_Revit_UI and not in Revit_Adapter because they reference Revit API and due to that reference it is impossible to move them.
- The methods sit in `Convert` class and it seems not to make sense to move them to `Create` as Engine's `Create` is fundamentally different from Adapter's `Create` (plus the methods would not be picked up by the API anyways).

Taken the above, it makes most sense to keep the methods where they are and use `ToRevit` names, at least for now, until we come up with a more sensible solution. I am closing this issue, please feel free to reopen it in case you disagree with anything stated in this comment.
