### ISSUE TITLE
Is UpdateValues method needed at all?

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#563]
#### Description

`BH.UI.Revit.Engine.Modify.UpdateValues` method is used on ToBHoM convert methods. Not sure what it does as it is used mainly by BEnv. Couldn't we either get rid of it or merge into `SetCustomData`?

**Comment by FraserGreenroyd** [comment]
Adding a `size:M` label as have reviewed the work on this and it isn't a few minutes to achieve >.<

**Comment by pawelbaran** [comment]
I am going to resolve this one in this sprint @FraserGreenroyd.
