### ISSUE TITLE
Revit_Toolkit: on null request Pull/Remove filters all ElementIds instead of nothing

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#611]
#### Description:

As in the title, on attempt to pull/remove with a `null` request, all elements in the model are processed. This happens because of `null` being converted to an empty `FilterRequest` in the BHoM_UI, which then triggers pulling everything.

**Comment by alelom** [comment]
Issue on BHoM UI: https://github.com/BHoM/BHoM_UI/issues/228
