### ISSUE TITLE
Revit_Toolkit: Migrate BH.Engine.Adapters.Revit.Query.CustomDataValue to Data_Engine

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#635]
#### Description:

The method definitely should not sit in the Revit_Toolkit. The question is, don't we have such method somewhere already? Or is there a reason not to have it?

https://github.com/BHoM/Revit_Toolkit/blob/957f1b8c485e437a1b4da6e78ff4de2c0b9a0e98/Revit_Engine/Query/CustomDataValue.cs#L39-L49

@IsakNaslundBh @al-fisher @adecler

**Comment by IsakNaslundBh** [comment]
GetProperty does this from the side of the UI, and from the code side, you might as well use `obj.CustomData[key]` or `bHoMObject.CustomData.TryGetValue(key, out obj)` value for that matter. As I assume methods using this in Revit_Toolkit are using nullchecks on the thing returned anyway, a simple tryGetValue will have identical results.

Do not really see any good reason to keep this method tbh.

**Comment by pawelbaran** [comment]
The thing is one needs to declare `obj` every time plus do the null checks - these 2 steps are not performed in the code atm and avoiding them is why I thought it is worth keeping the method as it is.
