### ISSUE TITLE
Revit_Toolkit: Migrate BH.Engine.Adapters.Revit.Modify.SetTag to BHoM_Engine

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#636]
#### Description:

The method definitely should not sit in the Revit_Toolkit. The question is, don't we have such method somewhere already? Or is there a reason not to have it?

https://github.com/BHoM/Revit_Toolkit/blob/957f1b8c485e437a1b4da6e78ff4de2c0b9a0e98/Revit_Engine/Modify/SetTag.cs#L40-L53

@IsakNaslundBh @al-fisher @adecler

**Comment by IsakNaslundBh** [comment]
Could see a use for this, but would put it in the base `BHoM_Engine` rather than the `Data_Engine`

**Comment by pawelbaran** [comment]
Right, good point - title changed.

**Comment by pawelbaran** [comment]
The method is gone, so the issue can be closed.
