### ISSUE TITLE
Revit_Toolkit: Unable to pull EnergyAnaslysisModel

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#674]
#### Steps to reproduce:

Unable to pull simple model
![image](https://user-images.githubusercontent.com/26113670/80098653-278d8a80-8565-11ea-980c-aee2f61f9dd3.png)
![image](https://user-images.githubusercontent.com/26113670/80098696-3a07c400-8565-11ea-806e-67abf8583855.png)

#### Expected behaviour:

valid Panels, Spaces, Levels and Building

**Comment by pawelbaran** [comment]
@michaldengusiak thanks for raising! However, it is impossible to resolve this issue constructively without more precise input from your end:
- which version of BHoM are you using?
- test file (.rvt file with the model)

To me it looks like some assemblies have not been rebuilt correctly, causing strange issues that should never appear.

The code is tested on ongoing basis and such behaviour has never been recorded.

**Comment by michaldengusiak** [comment]
@pawelbaran 

you are right here are more details:
I just build BHoM 5 min ago so I think is currently version

![image](https://user-images.githubusercontent.com/26113670/80100927-97514480-8568-11ea-99e0-1fd59ed6c49a.png)

here test file:
[Revit_Toolkit_Issue674.zip](https://github.com/BHoM/Revit_Toolkit/files/4522561/Revit_Toolkit_Issue674.zip)

**Comment by pawelbaran** [comment]
Everything works perfectly fine on me end @michaldengusiak, 24 elements come out of pull with a single note about default pull config:

![image](https://user-images.githubusercontent.com/26874773/80101843-40e90380-8572-11ea-9230-7aab53c2250b.png)

Looks like something did not build correctly for you.

**Comment by michaldengusiak** [comment]
@pawelbaran thanks I will delete all and try again

**Comment by michaldengusiak** [comment]
I deleted my BHoM from AppData\Roaming\BHoM, and rebuild all again, it does not solve it...
hmm any idea what else I could try?
![image](https://user-images.githubusercontent.com/26113670/80107615-3844fd00-8573-11ea-87ab-74f26b02c7e5.png)

**Comment by pawelbaran** [comment]
Please rebuild your Revit_Toolkit build folder

**Comment by michaldengusiak** [comment]
OK I deleted all again: AppData\Roaming\BHoM and whole Revit build folder
build again and still same  error,

**Comment by pawelbaran** [comment]
Hmm, then it might be one of the dependencies - could be worth cleaning all build folders and rebuilding whole BHoM from scratch.

**Comment by michaldengusiak** [comment]
ok, will try to clear all build folders...

**Comment by michaldengusiak** [comment]
it took me a while without CodeAssistant...
so I deleted  app data and all build folders and build one by one for VS again
![image](https://user-images.githubusercontent.com/26113670/80216762-7820e880-8636-11ea-9be6-823831e82005.png)

I tried GH
![image](https://user-images.githubusercontent.com/26113670/80216737-6fc8ad80-8636-11ea-93ea-fcc2182bc4b1.png)
and Dynamo... here I can not even create Adapter it is stopping on each node...
![image](https://user-images.githubusercontent.com/26113670/80216723-6b03f980-8636-11ea-8d88-ede5d6531eea.png)
hmm, it must be some settings I am not aware of.. hmmm any other tip I could try?

**Comment by michaldengusiak** [comment]
I just realized it is not installation Issue as I can pull Spaces and Building...
![image](https://user-images.githubusercontent.com/26113670/80218256-da7ae880-8638-11ea-8294-77c681947d3e.png)
![image](https://user-images.githubusercontent.com/26113670/80218269-e070c980-8638-11ea-9844-f4cdec4feb5b.png)

only can not this energy analysis
![image](https://user-images.githubusercontent.com/26113670/80218359-fe3e2e80-8638-11ea-9d22-7d5e3d7afa10.png)

**Comment by pawelbaran** [comment]
Are you sure you have the energy analysis model set up in Revit? For me it worked like a charm on the file you shared.

**Comment by michaldengusiak** [comment]
yes I do...do you want me to record video to proof and show process? 
![image](https://user-images.githubusercontent.com/26113670/80219627-a6a0c280-863a-11ea-95fb-781cbd0d1f25.png)

**Comment by pawelbaran** [comment]
No need... I ran out of ideas what could go wrong on your build 🐒 maybe you could try the installer?

**Comment by michaldengusiak** [comment]
ok I just tried installer https://bhom.xyz/ 
3.1 and this is message now
![image](https://user-images.githubusercontent.com/26113670/80234929-d6f35b80-8650-11ea-80aa-d94dc69b9629.png)

**Comment by michaldengusiak** [comment]
will try to uninstall and restart PC

**Comment by michaldengusiak** [comment]
ok I could install after reboot and second install,   but I have this error now
![image](https://user-images.githubusercontent.com/26113670/80235527-ba0b5800-8651-11ea-856d-98fda9b450e0.png)

**Comment by michaldengusiak** [comment]
I just deleted all again and I used old installer from January 2020,  
I guess this was before implementing a new approach and works fine for me on Revit 2020

![image](https://user-images.githubusercontent.com/26113670/80260938-face9580-8680-11ea-9f87-87553670703b.png)
even it is working on a complex template model and I can export gbXML, so something is not fully working in current version.... or I am missing sth
![image](https://user-images.githubusercontent.com/26113670/80261295-f48ce900-8681-11ea-9ac0-f277f078d136.png)

**Comment by pawelbaran** [comment]
Could you share both above test files again? I will double check if they work on my build (and debug if not). Thanks!

**Comment by michaldengusiak** [comment]
here you go, 
two Revit files and one GH,
I just rebuild all toolkit once again after XML merge, Revit merge and UI change

I can not pull Energy Analytical when I try to pull Panels I got this, I can see floor and roofs here

![image](https://user-images.githubusercontent.com/26113670/80388820-414f0a80-88a2-11ea-9664-bef4a9759fce.png)

[Revit_Toolkit_Issue674.zip](https://github.com/BHoM/Revit_Toolkit/files/4540478/Revit_Toolkit_Issue674.zip)

**Comment by michaldengusiak** [comment]
[Revit_Toolkit_Issue674_1.zip](https://github.com/BHoM/Revit_Toolkit/files/4540486/Revit_Toolkit_Issue674_1.zip)

**Comment by pawelbaran** [comment]
@michaldengusiak I gave it a shot on a build from current master, everything seems to be just fine:

![image](https://user-images.githubusercontent.com/26874773/80473469-790f8e00-8946-11ea-9a43-9f38eee63676.png)

![image](https://user-images.githubusercontent.com/26874773/80473497-83ca2300-8946-11ea-9c88-766d423c45d5.png)

This is a very peculiar issue - particularly the fact that Revit is throwing a managed exception, which apparently it should not do (see [this thread](https://forums.autodesk.com/t5/revit-api-forum/inconsistent-exception-exceptions-internalexception-occurred-in/td-p/7708788)).

Could you please try debugging the problem on your end? I believe the issue occurs inside `EnergyAnalysisModelFromRevit` convert method, so the recommended location for a break point would be line 41:

https://github.com/BHoM/Revit_Toolkit/blob/e600d76648efd73464b187fa027bad7a5d40cea3/Engine_Revit_UI/Convert/Environment/FromRevit/EnergyAnalysisModel.cs#L32-L43

**Comment by michaldengusiak** [comment]
ok a good news, I just installed current master from all repos again. 

I run debug mode..can see 
it is giving error here 
`internal static oM.Environment.Elements.Panel EnvironmentPanelFromRevit`
![image](https://user-images.githubusercontent.com/26113670/80507010-4083aa80-896e-11ea-83e2-04f4fd5227d4.png)

but it produces Model...
![image](https://user-images.githubusercontent.com/26113670/80507179-74f76680-896e-11ea-992c-d723f767fba5.png)

Do you want to follow this warning somewhere or this is expected behaviour?

**Comment by pawelbaran** [comment]
I will have a look into the error you have found. Thanks!

**Comment by michaldengusiak** [comment]
@pawelbaran 
I just realized something that I was running Rhino 7 WIP(Rhino.Inside) and it does not work for this version. as you can see below When I run normal Rhino and connect  to Revit it works


![image](https://user-images.githubusercontent.com/26113670/80510453-a6723100-8972-11ea-98b8-91e55105cd1f.png)

**Comment by pawelbaran** [comment]
Right, that explains the managed exception! Good point @michaldengusiak, big thanks!

@al-fisher @rwemay FYI - this needs to be investigated, #677 raised

**Comment by rwemay** [comment]
Thanks @michaldengusiak !!
