### ISSUE TITLE
Revit Pull Methods for Facilitating LCA

### ISSUE THREAD

**Issue by ajensen19** [BHoM/Revit_Toolkit#684]
#### Fuctionality:
In order to make our LCA-toolkit easily usable for projects that have Revit models, I suggest we set up a way to automatically sift through the endless Revit families (circled in red), identify which are in use in the Revit file, and pull and organize these geometries by unique family types (lets pretend those in use are highlighted in yellow). The family type is the level of detail I'd imagine working at in Revit. Perhaps this belongs in Revit-Toolkit but i don't know for sure so I kept it here for now!

![image](https://user-images.githubusercontent.com/19961672/80492207-b158a180-8931-11ea-9340-3df9fb43f3f8.png)

A rough sketch of such a concept is below, where when set to true the left side of the component populates with all the families in use in an open Revit model. Then the user can set each of those families to TRUE in order to confirm which families they'd like to pull the geometry from. The right side of the component would then spit out the geometry from all families which are set to TRUE and auto- organizes these into the unique family types. I realise this isn't a realistic component design given how the RevitAdapter operated but I hope this illustrates my point. 

![Revit Pull sketch](https://user-images.githubusercontent.com/19961672/80494314-87ed4500-8934-11ea-900d-da2156b23c97.jpg)

Given how the RevitAdapter is set up I imagine what I'm really looking for is actually two methods:
1. A method that returns the active Families in Revit which have objects in them, allows the user to select/confirm which they wish to pull from a list and constructs an appropriate FilterRequest for use in the inputs for the RevitPull. 
2. A method that takes the output from the RevitPull geometry, groups and organizes it into family types for easy use specifying.

**Comment by ajensen19** [comment]
Thanks for your suggestion, @enarhi ! 

I transferred this to the Revit toolkit for further discussion because I feel like I've hit some snags implementing the above methods and still believe these kinds of methods would facilitate a broader effort to use the BHoM methods for Revit models in house.

For example, the first feature which would check which Revit families are in use seems critical because in the current workflow im hunting and pecking around BHoM objects trying to figure out if I've got everything critical from Revit, with no easy way to verify this or what is in the Revit model in the first place. The first feature described above (perhaps a RevitQuery method?) would be provide ease-of-use and QA/QC at once. 

![image](https://user-images.githubusercontent.com/19961672/80757744-a9039080-8b02-11ea-8cda-2c0e569ee0f1.png)

The second feature about organizing geometry into family type containers could be super helpful for all us BHoM hopeful users that don't have the "data structure-computational prowess" to follow the list mapping process suggested above!

**Comment by rwemay** [comment]
I think pulling all family types in use is a good idea. Also a geometry comparer that identifies unique geometries within those (as there will be multiple versions of the same geometry but with different parameters etc) is also really useful. I think the former might be easier to implement in the short term if not already possible (as a single request rather than pulling all and filtering). @pawelbaran thoughts?

**Comment by pawelbaran** [comment]
I've started reading at the top, and felt like we are all having similar ideas! How I see it:
- `FilterFamilyTypesByUsage` (bool used, if `true` then all used family types, if `false` then all unused) - this should be an easy one
- the above can be combined with e.g. `FilterByCategory` to narrow down the filter and avoid overhead on converts
- getting geometry by type is unclear to me as geometry of many elements is parameter driven: instead, I would pull elements by type and then query geometry of each

How does that sound?

**Comment by ajensen19** [comment]
Hi @pawelbaran and @rwemay! thanks for the discussion and thoughts :) I also spoke with @enarhi  about this workflow yesterday who had a workflow in mind about setting up a selection set in Revit and then pulling by ParameterText which was doable with a bit of prep required in Revit (see snip of this below). Pawel's suggested "FilterFamilyTypesByUsage" also sounds great on my end, and would perhaps eliminate the need to prep in Revit. Is "FilterFamilyTypesByUsage" an existing method or would that be an additional lift to make?

![image](https://user-images.githubusercontent.com/19961672/81183231-e477e200-8f7c-11ea-8de5-ac69f96daf23.png)
[Revised Revit Pull for LCA.zip](https://github.com/BHoM/Revit_Toolkit/files/4587113/Revised.Revit.Pull.for.LCA.zip)

My only other question is can I "FilterByCustomDataField"? Say I want to separate out these BHoM slab objects by Revit_categoryName, Revit_familyName or sometimes even Revit_familyTypeName? Thanks all for helping out a fresh user like me!

![image](https://user-images.githubusercontent.com/19961672/81183959-cf4f8300-8f7d-11ea-8acc-eccd2d4293f7.png)

**Comment by rwemay** [comment]
On filtering object, search for 'filterby' component, and you should be able to filter by any property/customdata based on name and value. It's string based at the moment, but we'll expand this later. Should work for your purposes.

**Comment by pawelbaran** [comment]
Following @rwemay, there is a range of `FilterByParameter` filters, however, you can only filter by Revit parameters - so family name may not work. What can be more suitable is `FilterByFamilyAndTypeName` or `FilterByCategory`.

Joining two filters into logical OR and AND statements can be done with `LogicalOrRequest` and `LogicalAndRequest` respectively ([link](https://github.com/BHoM/Revit_Toolkit/wiki/Requests-and-filtering#special-requests) and [link](https://github.com/BHoM/Revit_Toolkit/wiki/Pull-examples#advanced-filters)).

In general, I strongly recommend exploration of all `FilterBy` requests, most likely you can stitch them together to achieve your goals. In the meantime, I will raise an issue requesting implementation of `FilterFamilyTypesByUsage`.

**Comment by rwemay** [comment]
Thanks @pawelbaran . The `FilterBy` requests will only work with pull/requests, correct? So you'd have to construct the logic at pull.  `BH.Engine.Data.Query.FilterBy' will work on any BHoM object after pull. 

Assuming the pull/requests don't work beyond pull, we do need to port across the same filter logic to the data engine. One to add to the list!

**Comment by enarhi** [comment]
Agreed @rwemay , and I think the key one to add as high priority is a GroupBy that uses the same logic as FilterBy without requiring input values for the property. This would eliminate the need to get all property values, find unique, then filter by usng list management, which can be a bit of a headache for more novice users. Expected functionality would be list of randomly organized objects in>lists of lists of objects out where each list is all objects with the same property value, and possibly also an output telling you the property value that corresponds to each list.

**Comment by pawelbaran** [comment]
O wow, I did not know about the existence of `FilterBy` in Data_Engine @rwemay! I confused Revit filter requests with that one - sorry for that.

@enarhi looks like what you are missing is `FilterFamilyTypesByUsage` and `GroupByProperty` - correct me if I am wrong.

**Comment by pawelbaran** [comment]
Please see https://github.com/BHoM/Revit_Toolkit/pull/706
