### ISSUE TITLE
Revit_Toolkit: Push Foundation Walls

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Revit_Toolkit#69]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
@IsakNaslundBh I guess we would need to start from implementing the foundation-related classes in the oM?

**Comment by pawelbaran** [comment]
I am closing this issue until the foundation objects get added to the oM.
