### ISSUE TITLE
Revit_Toolkit: implement a framework to load/build cross section families while pushing BHoM bars to Revit

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#70]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
Adding @JosefTaylor to the issue as a volunteer to resolve it.

I believe the easiest way of making this happen would be to create a range of .rfa files per each section shape and element type (beam/column), ship these with Revit_Toolkit and simply load with the right dimensions, name and parameters to the model on push of a `ConstantFramingProperty` (`BH.Revit.Engine.Core.Query.ElementType` could be extended to enable that). The painful step here would be storing the Revit families in the installer, say 10 shapes x 2 types x 0.5mb each = 10mb of Revit data shipped with BHoM. How would you feel about that @al-fisher?

An alternative would be to create everything from scratch programatically, including the profile curves and their constraints with regard to the centroid etc., which is also possible but would require much more effort on the dev side.

**Comment by JosefTaylor** [comment]
There are a number of situations which need to be accommodated: 

1. Pushing commonly available catalogue sections, which might be available from an already loaded family .rfa (already possible)
2. Pushing sections which conform to our BHoM standard parametric shapes, like I-shapes, rectangular tubes, round tubes, channels, etc. which can be parametrically defined (done via @pawelbaran's suggestion above)
3. Pushing generic sections with who knows what profile, which would involve creating a brand new family for each one, creating sketches in that family, etc. 

seems like doing 1 and 3 would cover all bases, but be hard to do. 1 and 2 would cover most bases and be simple, but requires 10MB of revit data in the installer.

**Comment by pawelbaran** [comment]
> There are a number of situations which need to be accommodated:
> 
> 1. Pushing commonly available catalogue sections, which might be available from an already loaded family .rfa (already possible)
> 2. Pushing sections which conform to our BHoM standard parametric shapes, like I-shapes, rectangular tubes, round tubes, channels, etc. which can be parametrically defined (done via @pawelbaran's suggestion above)
> 3. Pushing generic sections with who knows what profile, which would involve creating a brand new family for each one, creating sketches in that family, etc.
> 
> seems like doing 1 and 3 would cover all bases, but be hard to do. 1 and 2 would cover most bases and be simple, but requires 10MB of revit data in the installer.

1. Would always go first, 2. or 3. would only trigger if the type is not found in the model or loaded library. I believe 3. should be relatively easy to implement if it is only meant to work with `FreeFormProfile` - then you can open any random template used for 2., remove all constraints and geometry and redraw it from scratch. The key part here is lack of need for geometrical constraints in case of a freefrom profile - these I would expect to be the worst pain of all. That is at least how I thought it through 🙈

**Comment by JosefTaylor** [comment]
Agreed - 3 is straightforward, just might be difficult. Also I want to make sure we do 1 first- right now if you supply a catalogue section and don't tell it what .rfa to load it from, and there's no existing family matching that name, it fails to make it, which is fine. if we implement 3, all those will be created as individual things, which would be really annoying! I guess if it's restricted to freeforms, that would be ok, but not as flexible.

**Comment by JosefTaylor** [comment]
Also- we now have support for tapered sections in BHoM, and if we're creating a new family anyway, it might be the right time to support that.

**Comment by pawelbaran** [comment]
Not sure how often the tapered cross sections are actually used - if you believe it is worth our time, let's record it and try to tackle. However, I would do that in a separate issue/PR to reduce the size and complexity of each thread.

**Comment by JosefTaylor** [comment]
I've used tapered profiles on two projects in as many years, though I didn't put em through the BHoM. Can't justify building a bridge by counting the folks swimming across!

**Comment by pawelbaran** [comment]
This issue has been closed via #1225.
