### ISSUE TITLE
Pull Fails for Large OOTB Revit HSS Circular Column Families

### ISSUE THREAD

**Issue by enarhi** [BHoM/Revit_Toolkit#703]
#### Description:
Pull currently fails for Revit's OOTB HSS circular columns when pulling as bars.

#### Steps to reproduce:
Pull structural from a revit model containing HSS##X### circular columns. An error occurs, "1. BHoM object could not be properly converted. Element Id: 2754705, Element Name: HSS20X0.500, Exception Message: Unable to cast object of type 'BH.oM.Geometry.Arc' to type 'BH.oM.Geometry.PolyCurve'."

#### Expected behaviour:
HSS Columns pull the same as other elements.

**Comment by rwemay** [comment]
Have we checked the OOTB content? I seem to remember a previous issue where the arc geometry in the content wasn't quite right...

**Comment by enarhi** [comment]
Upon further testing, this appears to happen only on large HSS profiles with low thicknesses. For example, HSS20X0.500 and HSS20X0.750 fails, while an HSS20X1.00 works.

**Comment by pawelbaran** [comment]
@enarhi could you please upload minimum test content (a .rvt model with single element that breaks + .gh script that highlights it)? It would make it much easier for me to tackle. Thanks!

**Comment by enarhi** [comment]
Sure thing. See below for R19 model with problem sections and working sections, along with a gh script.

![image](https://user-images.githubusercontent.com/6752345/82350033-ada7c000-99af-11ea-976d-55eed91a4b07.png)

[Revit Problem Sections.zip](https://github.com/BHoM/Revit_Toolkit/files/4651680/Revit.Problem.Sections.zip)

**Comment by pawelbaran** [comment]
This turned out to be an issue in the Structure_Engine, logged in https://github.com/BHoM/BHoM_Engine/issues/1795 - closing this one as not relevant to Revit_Toolkit.
