### ISSUE TITLE
Revit_Toolkit: RevitAdapter GH node loses contact if it recomputes while Revit is open

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Revit_Toolkit#71]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
Closing this one as possibly resolved or a duplicate of #257
