### ISSUE TITLE
Revit_Toolkit: Set up for Revit 2021

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#717]
#### Description:

Revit 2021 has been released publicly, support needed.

**Comment by FraserGreenroyd** [comment]
Can I suggest we do this as a 3.3 task? Unless there is no desire to include this in an installer this milestone? It seems risky to try and put in an additional version before end of next week.

**Comment by pawelbaran** [comment]
Right, this is not going to happen that quickly, which will be an issue for the installer.

However, would it be possible to set it up in 3.2 but start including in the installer from 3.3?

**Comment by FraserGreenroyd** [comment]
Yeah that sounds fine, just didn't want to risk overloading workload fro this sprint :smile:
