### ISSUE TITLE
Revit_Toolkit: Adapt to changes to PlanarSurface

### ISSUE THREAD

**Issue by kThorsager** [BHoM/Revit_Toolkit#722]
Again

#### Parent issue(s) or Pull Request(s) causing the changes:

https://github.com/BHoM/BHoM/issues/877
We made `PlanarSurface` `IImmutable` poorly, which will have to be resolved.

#### Description:

c:\github\revit_toolkit\engine_revit_ui\query\planarsurfacedictionary.cs
uses the Internal Openings List as a list, which isn't possible after we switch to` ReadOnlyCollection`. and since it uses it by reference I'm vary of trying to fix it myself.

#### Test file(s):

Not broken yet

**Comment by pawelbaran** [comment]
@kThorsager I just had a look at that - seems to be a bit tricky and I would prefer not to change it now, out of nowhere. However, I am planning to refactor this method in this Milestone, so happy to take on that later in June. Would it be OK to freeze the refactoring of `PlanarSurface` until then?

**Comment by kThorsager** [comment]
Yes, I think this way of treating it should be unusual enough that it isn't pressing enough to mess up Revit_Toolkit
👍

**Comment by al-fisher** [comment]
Agreed - sounds like a fine plan

**Comment by pawelbaran** [comment]
Bumping to 3.3 as it seems not to be the right moment to implement that change.
