### ISSUE TITLE
Revit_Toolkit: Information duplicated on BEnv converts

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#725]
#### Description:

`EnvironmentPanelFromRevit` and `OpeningFromRevit` copy over the underlying type parameters to BHoM object's `CustomData`, even though they are also copied to `CustomData` of this same object's `Construction`.

https://github.com/BHoM/Revit_Toolkit/blob/7066dfab9a4bedf8ac000dfdb241c4ff7080d49c/Engine_Revit_UI/Convert/Environment/FromRevit/Panel.cs#L497-L498

https://github.com/BHoM/Revit_Toolkit/blob/7066dfab9a4bedf8ac000dfdb241c4ff7080d49c/Engine_Revit_UI/Convert/Environment/FromRevit/Opening.cs#L102-L103

@FraserGreenroyd is that necessary?

**Comment by FraserGreenroyd** [comment]
No they are not necessary anymore and I would be happy for you to remove them :smile:

**Comment by pawelbaran** [comment]
Thanks @FraserGreenroyd. Could please also check whether _Family Type_ parameter does need to be copied over to a converted `Panel` from its `Construction`? It looks like a one-odd method call with no peer in the whole code base.

https://github.com/BHoM/Revit_Toolkit/blob/7066dfab9a4bedf8ac000dfdb241c4ff7080d49c/Engine_Revit_UI/Convert/Environment/FromRevit/Panel.cs#L495

**Comment by FraserGreenroyd** [comment]
It isn't required in custom data as far as I'm concerned @pawelbaran so would be happy with that line being removed too.
