### ISSUE TITLE
Revit_Toolkit: Framing pulls at the centerline, but pushes back in at the justification point

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Revit_Toolkit#740]
#### Description:
I'm attempting to update section properties for beams via GH. So, I pulled revit FramingElement.Beam, changed the Property, and the pushed them back with PushType UpdateOnly. The beams each dropped half their depth.

#### Steps to reproduce:
pull Beams, then push them back in using UpdateOnly. They will be lowered.

#### Expected behaviour:
What comes in should match what goes out.

**Comment by pawelbaran** [comment]
Hi @JosefTaylor, could you please give some more info on the beams in Revit, particularly about their justification and offset parameters before/after update? This is a recurring issue that I am planning to resolve in the coming weeks, so the more info the better. Thanks!
