### ISSUE TITLE
Revit_Toolkit: Pulling panels to return valid BHoM panels (provided panel was valid in Revit)

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Revit_Toolkit#770]
#### Description:
Currently Revit's tolerance for curve planarity and closure of polycurves is a bit sloppier than BHoMs, resulting in many panels coming out of Revit needing to be recomputed or collapsed to polylines. These cleanup steps should be done inside the Read method to avoid additional effort by the user in cleaning up apparently clean geometry, with a note if the difference in area/distance exceeds some threshold (such as the BHoM tolerance level)

**Comment by pawelbaran** [comment]
@JosefTaylor could you please share a test file that would allow to replicate your issue? That would be really helpful. Thanks!

**Comment by pawelbaran** [comment]
Following the chat with @JosefTaylor, the issue seems to be resolved with #796, therefore closing this.
