### ISSUE TITLE
Revit_Toolkit: Implement a variation GetRevitParameterValue that would allow string matching

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#788]
#### Description:

...so that one could get e.g. a value of parameter that starts with X or contains X. Would be good to leverage/unify with the mechanism used by `FilterByParameterText`.

**Comment by vietle-bh** [comment]
The tools consuming GetRevitParameterValue can do string matching themselves as it'll likely be specific to their particular task. Shall we close this issue?

**Comment by pawelbaran** [comment]
Hmm, the issue has been open for almost 3.5 years already without being dusted off, so I believe the feature is not overly needed. And as you've said @vietle-bh, it should be possible to achieve the effect by juggling the `RevitParameter` objects a bit.

Happy to close, @enarhi please reopen if you still need it 👍
