### ISSUE TITLE
Revit_Toolkit: Remove OriginContextFragment from non-BEnv converts

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#794]
#### Description:

Currently the following convert methods attach `BH.oM.Environment.Fragments.OriginContextFragment` to the output, even though it comes from `Physical` namespace:
- `DoorFromRevit`
- `WindowFromRevit`
- `CeilingsFromRevit`
- `RoomFromRevit`

`OriginContextFragment` should be moved out to the BEnv convert side or simply deleted. @FraserGreenroyd could you please make a decision which scenario should be taken?

**Comment by FraserGreenroyd** [comment]
@pawelbaran I have done a review and a discussion and am happy with the `OriginContextFragment` coming off all/any Physical objects where appropriate and only remaining on Environments Analytical Objects :smile:
