### ISSUE TITLE
Revit_toolkit: Setrevitparameters

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/Revit_Toolkit#795]
#### Description:
The setRevitparameters requests inputs match regarding the number of items provided.

#### Steps to reproduce:
Provide the component with a tree of objects and a tree of values but only an item for paramNames

#### Expected behaviour:
Component should be able to function using a single item for inputs , 'values' and 'paramNames'

**Comment by pawelbaran** [comment]
@jdarcyBHE could you please try `SetRevitParameter` instead of `SetRevitParameters`? I think it should do the job (please mind that it had been added after the latest Beta release though).

**Comment by jdarcyBHE** [comment]
Excellent thanks Pawel, I was working off the previous setup/logic of the setproperty
