### ISSUE TITLE
Revit_Toolkit: Introduce Revit => BHoM converts for linear MEP elements

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#826]
#### Description:

Following https://github.com/BHoM/BHoM/pull/953 and https://github.com/BHoM/BHoM_Engine/pull/1911, the next step will be adding Revit => BHoM converts for core linear MEP objects:
- [ ] pipes
- [ ] ducts
- [ ] wires

The code structure is very likely to be similar to the one for `Bar` converts:
- convert the location from Revit
- convert the materials from Revit (a separate convert to `IMEPMaterial` needed)
- convert the profile from Revit (would be good to make use of the existing code base used by structural profiles if applicable)
- create BHoM element property based on the converted materials and profile
- create the output based on the location and property

The intervention should be needed only in the _Revit_Core_Engine_ project, in `Convert` and `Query` classes, starting from _FromRevit.cs_ file.

**Comment by kayleighhoude** [comment]
![image](https://user-images.githubusercontent.com/34316256/91453937-5a66c880-e84e-11ea-9ad9-b867daafdd6b.png)

The above image displays the properties that should be converted from Revit. The thickness of the duct itself can default to 16 gauge (0.001519 m) for the time being.
