### ISSUE TITLE
Revit_Toolkit: Local rotation of Duct members 

### ISSUE THREAD

**Issue by michaelhoehn** [BHoM/Revit_Toolkit#840]
#### Description:

OrientationAngle of Duct members is currently hardcoded and should be investigated and fixed. This property refers to the plan view rotation angle, not the slope of the duct. 

#### Steps to reproduce:

Pull any Duct object from a Revit file into a GH canvas and view the OrientationAngle value. 

#### Expected behaviour:

OrientationAngle should be accurately captured.

**Comment by pawelbaran** [comment]
Fixed with #847.
