### ISSUE TITLE
Revit_Toolkit: Pulled MEP SectionProperty values do not work

### ISSUE THREAD

**Issue by michaelhoehn** [BHoM/Revit_Toolkit#846]
#### Description:

This image is showing a pulled duct (red) and it's zero values for all area results. Conversely, the creation of a duct using the same parameters (green) results in correct values. This suggests the code does not yet implement these methods correctly.

![DuctError](https://user-images.githubusercontent.com/54593392/93259589-16d8ed80-f76e-11ea-93de-6b49a82c90c4.png)

#### Steps to reproduce:

Pull any duct and query any of the following properties. 
- ElementSolidArea
- ElementVoidArea
- LiningSolidArea
- LiningVoidArea
- InsulationSolidArea
- InsulationVoidArea

**Comment by michaelhoehn** [comment]
FYI @kayleighhoude @FraserGreenroyd @pawelbaran

**Comment by pawelbaran** [comment]
Fixed with #847.
