### ISSUE TITLE
Steel sections without material assigned pull as generic

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Revit_Toolkit#882]
#### Description:

When pulling a structural framing element, if the material has not been assigned, the resulting BHoM framing element has a material 'Unknown Steel Material' but the section is a generic, rather than a steel section. If we know it is steel, we should assign it a default steel material, so that at least it comes through as the proper section type.

#### Steps to reproduce:

Create some framing elements or columns in Revit, and don't assign the Structural Material. Pull these with BHoM and get AnalyticalBars - AnalyticalBars throws an error:
"The material with name Unknown Steel Material is not a valid structural material as it does not contain exactly one structural material fragment. An empty generic isotropic material has been assumed"

#### Expected behaviour:

Assign a default steel or concrete material (it can still be called Unknown Steel Material) rather than a material with no structural fragment.

**Comment by pawelbaran** [comment]
Thanks for reporting @JosefTaylor, I have added it to the 4.0 as it should be a rather quick fix. However, I will rather look into it closer to the end of the milestone due to other more urgent tasks hanging atm - please shout if that needs prioritizng!
