### ISSUE TITLE
Revit_Toolkit: Push of a PanelPlanar needs a better way to determine whether a panel is a wall or a floor

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#90]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
This should be solved by implementation of Physical Objects ([BHoM PR](https://github.com/BHoM/BHoM/pull/418))

**Comment by epignatelli** [comment]
Moving this to the 2.4 RC milestone, since it is labelled as bug.

**Comment by pawelbaran** [comment]
Closed with #376.
