### ISSUE TITLE
Introduce graphs to LocationCurveMEP

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#905]
#### Description:

Following https://github.com/BHoM/BHoM/pull/1036, it would be good to leverage the graph implementation to extract location curves of the MEP elements.

**Comment by tiagogrossi** [comment]
@rolyhudson we raised this issue here in Revit_Toolkit but I'd rather we tackle that in the Analytical_oM/Engine, in such a way that I can easily plug an MEP `IFlow` into a graph. Therefore I think we can close this issue @pawelbaran ?

**Comment by pawelbaran** [comment]
Sounds good to me. However, my intuitive choice of an engine would be Spatial_Engine. Happy to be corrected though!

Please feel free to close the issue if you find it redundant.

**Comment by pawelbaran** [comment]
Not relevant, @travispotterBH is on it now with new issues and dev plans.
