### ISSUE TITLE
Revit_Toolkit: Wall and Floor Openings

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/Revit_Toolkit#91]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
@ZiolkowskiJakub Don't we now have this with skylights/rooflights?

**Comment by michaldengusiak** [comment]
as @ZiolkowskiJakub need confirmation, I will start a discussion here so we can clarify and unify method. Currently, when we pulling physical roof we have cut for openings when we pull walls we do not have. 
I would prefer to delete opening cut for the roof when we pulling Roof or alternatively add a method that returns us Roof without opening
 
![image](https://user-images.githubusercontent.com/26113670/65024515-f0029400-d92c-11e9-811a-2f86fafc2765.png)

**Comment by FraserGreenroyd** [comment]
So from my understanding, both `Physical.Wall` and `Physical.Roof` share the same properties, of a `Geometry.ISurface` location and a collection of `Physical.Opening` (which can be `window`, `door`, etc.).

I would therefore expect them to work in the same way, that pulling a `Wall` and a `Roof` provided similar results. To me, the use of `ISurface` as the geometric representation suggests we should be cutting out the `Opening` parts of `Wall` and `Roof` and leaving them as holes which can be filled by the representations of the `Opening` the object hosts.

Therefore, to me, in this example we should be pulling `Physical.Wall` with openings same as `Physical.Roof`.

Also, just as a last note, we should only assign the people to issues who are going to work on the code. If we want to specifically alert someone to this issue for their input the best way is to do an FYI at the end (e.g. FYI: @al-fisher ) to keep the issue fully up to date :smile:

**Comment by pawelbaran** [comment]
Closing as likely to be resolved with #376.
