### ISSUE TITLE
MEP Linear elements updates from oM refactor

### ISSUE THREAD

**Issue by michaelhoehn** [BHoM/Revit_Toolkit#948]
#### Description:

See oM issue https://github.com/BHoM/BHoM/issues/1139 for proposed functionality changes.

**Comment by pawelbaran** [comment]
@michaelhoehn is it still relevant or can we close?

**Comment by pawelbaran** [comment]
I guess we can close, taken it was open for many months with no action 😉 please feel free to reopen if needed though.
