### ISSUE TITLE
FreeFormProfiles come out flipped around their local Y axis on pull

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#972]
#### Description:

Test files are [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%23972%2DFreeFormProfileBugs&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

As in the title, well spotted by @LMarkowski. Actually, there are 2 issues strictly related to that:
- on pull, non-symmetrical profiles come out flipped, as in the title
- if the element in mirrored in Revit, the profiles still come out without the mirror - @IsakNaslundBh, how would you handle mirroring of profiles, e.g. imagine two parallel beams with profiles as below, should they have separate profile definitions or is there another way of defining that?
    ![image](https://user-images.githubusercontent.com/26874773/108061273-5b87ee00-7058-11eb-8802-69b22feb9833.png)

**Comment by IsakNaslundBh** [comment]
> if the element in mirrored in Revit, the profiles still come out without the mirror - @IsakNaslundBh, how would you handle mirroring of profiles, e.g. imagine two parallel beams with profiles as below, should they have separate profile definitions or is there another way of defining that?

There are mirror booleans on the asymmetric profiles. Hopefully they could help?

https://github.com/BHoM/BHoM/blob/735e9dae4b97f1e4d514f4b1651bf3c1942ecfb7/Spatial_oM/ShapeProfiles/AngleProfile.cs#L64-L68

https://github.com/BHoM/BHoM/blob/735e9dae4b97f1e4d514f4b1651bf3c1942ecfb7/Spatial_oM/ShapeProfiles/TSectionProfile.cs#L64-L65

https://github.com/BHoM/BHoM/blob/735e9dae4b97f1e4d514f4b1651bf3c1942ecfb7/Spatial_oM/ShapeProfiles/ChannelProfile.cs#L64-L65

**Comment by pawelbaran** [comment]
Thanks @IsakNaslundBh, that is exactly what I needed!
