### ISSUE TITLE
Pipe diameter issue on pull

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#981]
#### Description:

On pull of pipes, the diameters seem to come out mismatched:

![image](https://user-images.githubusercontent.com/26874773/110367538-16981b80-8048-11eb-874f-0fabdb864400.png)

**Comment by AndreBalasian** [comment]
@pawelbaran Thank you for identifying the issue and you assistance with replicating it.
The screenshot below shows a replicated issue with the appearance of diameters.
![image](https://user-images.githubusercontent.com/28534672/111637116-0b37b380-87f1-11eb-9143-c694593a39c9.png)
I am investigating the cause of the problem.

**Comment by AndreBalasian** [comment]
Insulation diameter check:
With the exception of some rounding of decimal places and having different units, the outer diameter of insulation checks out as shown below: 
Large pipe:
![image](https://user-images.githubusercontent.com/28534672/111654828-0549ce80-8801-11eb-9263-b981749e0723.png)
![image](https://user-images.githubusercontent.com/28534672/111654411-a421fb00-8800-11eb-96d8-9fe7a69dbc73.png)

Small pipe:
![image](https://user-images.githubusercontent.com/28534672/111656340-56a68d80-8802-11eb-99e7-447f1c316e47.png)
![image](https://user-images.githubusercontent.com/28534672/111656439-6faf3e80-8802-11eb-89ce-7a35346803d2.png)

Will check the pipe diameters to see if the problem originates there.

**Comment by AndreBalasian** [comment]
Pipe diameter test:

Based on the screenshots below, it appears that we are pulling the "nominal" pipe size and placing it in the Diameter property, which the description refers to as an Outer diameter.
This may explain why the Grasshopper visualisation looks different, as the nominal size is neither an inner or outer diameter. 

![image](https://user-images.githubusercontent.com/28534672/111660385-edc11480-8805-11eb-9f79-83a35af5ef3b.png)

Large pipe:
![image](https://user-images.githubusercontent.com/28534672/111662603-f9add600-8807-11eb-9057-a6f71c78f4ae.png)
![image](https://user-images.githubusercontent.com/28534672/111658421-3f689f80-8804-11eb-89ef-0b4e01f8cc4a.png)

Small pipe:
![image](https://user-images.githubusercontent.com/28534672/111662242-ab003c00-8807-11eb-867a-8c5a1685a4f9.png)
![image](https://user-images.githubusercontent.com/28534672/111661115-a6875380-8806-11eb-84b7-f19c3b1b3084.png)

**Comment by AndreBalasian** [comment]
This observation is confirmed in the code:
![image](https://user-images.githubusercontent.com/28534672/111762072-7c7e7180-8898-11eb-964f-defcc9fe7329.png)

**Comment by pawelbaran** [comment]
Well spotted @AndreBalasian. From what I can see it should be `RBS_PIPE_OUTER_DIAMETER`

![image](https://user-images.githubusercontent.com/26874773/111772717-79da4700-88ad-11eb-9d28-42356b34eddb.png)

**Comment by pawelbaran** [comment]
After the discussion with @AndreBalasian, we decided to park this issue until the nominal and physical dimensions are distinguished on the oM side (see [my comment](https://github.com/BHoM/BHoM/issues/1139#issuecomment-802773827)).

**Comment by travispotterBH** [comment]
Reviving this issue. 

We are unable to pull pipes of type Cast Iron at 1" due thickness being "inconceivable"

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/96432552/175435917-a17db099-d579-4330-9cbb-dbb38f49d8fd.png)


I propose a simple change from: 
![image](https://user-images.githubusercontent.com/96432552/175435994-c3d9f2a6-1a61-402c-aa81-e5c7251f5845.png)


to: 
![image](https://user-images.githubusercontent.com/96432552/175435971-8c5b91b5-788b-4f87-9144-a5264b44877a.png)

this would mean that any method that calls `Create.TubeProfile` would be using the outside diameter as it's diameter. Given that the thickness is also passed along, it is not apparent that the nominal diameter should be used since it is often not correct except for when ordering the pipe. 

Example from[ EngineeringToolbox](https://www.engineeringtoolbox.com/nominal-wall-thickness-pipe-d_1337.html): 
![image](https://user-images.githubusercontent.com/96432552/175436301-4cac05b9-bc61-495a-a3c4-f0302fe0cffa.png)

**Comment by pawelbaran** [comment]
Thanks @travispotterBH for picking this up. Looks like we are on the same page: let's first sort out https://github.com/BHoM/BHoM/issues/1139 (tricky bit for you guys - possibly something to brainstorm around and map out in the coming milestone?), then this issue should become super simple.

**Comment by vietle-bh** [comment]
@pawelbaran : I ran the Pipe-pulling script again and looks like it gave the correct pipe sizes compared to your screenshot in this issue's description. Have you already fixed this issue?

![image](https://github.com/BHoM/Revit_Toolkit/assets/102604891/874d32c2-5df6-478b-8e2c-dd2cccdd0edd)

![image](https://github.com/BHoM/Revit_Toolkit/assets/102604891/48f866fb-4ca1-4e85-b251-7e7b7f34506e)

**Comment by pawelbaran** [comment]
Hmm, we may have fixed it in the process, happy to close then.

@travispotterBH I am not sure whether the issue raised in your comment about cast iron still occurs, but if so, then I would suggest raising a separate, dedicated issue - discussion here started becoming a bit messy plus the originally reported problem does not exist any more.
