### ISSUE TITLE
Introduce a way of applying host element information to pushed objects

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#990]
#### Description:

Some BHoM objects pushed to Revit are meant to become hosted Revit elements, so they require the information about the host being passed to Revit somehow. Currently that has been the case only for `ModelInstances` and was resolved by using `HostId` property. However, that does not scale nicely, e.g. Physical reinforcement does not have (and will never have) such property, so currently a temp solution based on `CustomData` is used (see #956).

There is a need for an universal solution: my idea is to introduce a `RevitHostIdFragment` that could be added to virtually any object before push. Happy to hear others' opinion @alelom @IsakNaslundBh @LMarkowski (please stop me if this does not make sense 🐒).

**Comment by kayleighhoude** [comment]
![image](https://user-images.githubusercontent.com/34316256/133839265-036756b0-3ddc-43ce-8b89-904eb55b5442.png)

Might be related @pawelbaran
