### ISSUE TITLE
Revit_Adapter: Support creation of Filled Region Types and creation of new project parameters

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Revit_Toolkit#993]
#### Description:

In order to push load map data from Excel (where it is authored) to Revit, I need to create new filled region types corresponding to each set of loads, and create type parameters for Detail Items (unfortunately I cannot contain them to Filled Region Types). Once these are created, I can update them from BHoM with the correct hatch, type mark, parameter values, etc., but there's a lot of effort in creating these (and getting all the names right).

Generalized, this means creating new `InstanceProperties` i.e. Family Types in Revit and also creating new project parameters.

Alternately, a solution specific to Filled Regions is possible: a new BHoM object `FilledRegionType` which can be pushed to Revit. This still requires the general ability to add project parameters

Lastly, another approach would be to create a new Revit family more suited to load map use, which would have parameters built in with generic names (e.g. LoadArea Value1, LoadArea Value2, etc.), which could be ether renamed to match the names of loads, or could be scheduled in a way as to change the names of headers to names stored in another set of parameters (e.g. LoadArea Name1, LoadArea Name2, etc.)

**Comment by pawelbaran** [comment]
After further discussion with @JosefTaylor, I will do the 1st iteration of this and try to generalise the problem to creation of _any_ Revit type - if that fails, we will scale down to a problem-specific solution.
